[project]
name = "backend"
version = "0.1.0"
description = "FastAPI backend for the scheduler"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pydantic",
    "apache-dolphinscheduler==3.1.2",
]

[tool.uv.pip]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"
