package com.example.scheduler.model.autoGenerated;

import java.io.Serializable;
import java.util.Date;

public class EtlTaskMock implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etl_task_mock.task_id
     *
     * @mbg.generated
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etl_task_mock.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etl_task_mock.run_date
     *
     * @mbg.generated
     */
    private Date runDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.etl_task_mock
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etl_task_mock.task_id
     *
     * @return the value of public.etl_task_mock.task_id
     *
     * @mbg.generated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etl_task_mock.task_id
     *
     * @param taskId the value for public.etl_task_mock.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etl_task_mock.status
     *
     * @return the value of public.etl_task_mock.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etl_task_mock.status
     *
     * @param status the value for public.etl_task_mock.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etl_task_mock.run_date
     *
     * @return the value of public.etl_task_mock.run_date
     *
     * @mbg.generated
     */
    public Date getRunDate() {
        return runDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etl_task_mock.run_date
     *
     * @param runDate the value for public.etl_task_mock.run_date
     *
     * @mbg.generated
     */
    public void setRunDate(Date runDate) {
        this.runDate = runDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etl_task_mock
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", taskId=").append(taskId);
        sb.append(", status=").append(status);
        sb.append(", runDate=").append(runDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}