package com.example.scheduler.model.autoGenerated;

import java.io.Serializable;
import java.math.BigDecimal;

public class QrtzSimpropTriggers extends QrtzSimpropTriggersKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_simprop_triggers.str_prop_1
     *
     * @mbg.generated
     */
    private String strProp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_simprop_triggers.str_prop_2
     *
     * @mbg.generated
     */
    private String strProp2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_simprop_triggers.str_prop_3
     *
     * @mbg.generated
     */
    private String strProp3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_simprop_triggers.int_prop_1
     *
     * @mbg.generated
     */
    private Integer intProp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_simprop_triggers.int_prop_2
     *
     * @mbg.generated
     */
    private Integer intProp2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_simprop_triggers.long_prop_1
     *
     * @mbg.generated
     */
    private Long longProp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_simprop_triggers.long_prop_2
     *
     * @mbg.generated
     */
    private Long longProp2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_simprop_triggers.dec_prop_1
     *
     * @mbg.generated
     */
    private BigDecimal decProp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_simprop_triggers.dec_prop_2
     *
     * @mbg.generated
     */
    private BigDecimal decProp2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_simprop_triggers.bool_prop_1
     *
     * @mbg.generated
     */
    private Boolean boolProp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_simprop_triggers.bool_prop_2
     *
     * @mbg.generated
     */
    private Boolean boolProp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.qrtz_simprop_triggers
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_simprop_triggers.str_prop_1
     *
     * @return the value of public.qrtz_simprop_triggers.str_prop_1
     *
     * @mbg.generated
     */
    public String getStrProp1() {
        return strProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_simprop_triggers.str_prop_1
     *
     * @param strProp1 the value for public.qrtz_simprop_triggers.str_prop_1
     *
     * @mbg.generated
     */
    public void setStrProp1(String strProp1) {
        this.strProp1 = strProp1 == null ? null : strProp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_simprop_triggers.str_prop_2
     *
     * @return the value of public.qrtz_simprop_triggers.str_prop_2
     *
     * @mbg.generated
     */
    public String getStrProp2() {
        return strProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_simprop_triggers.str_prop_2
     *
     * @param strProp2 the value for public.qrtz_simprop_triggers.str_prop_2
     *
     * @mbg.generated
     */
    public void setStrProp2(String strProp2) {
        this.strProp2 = strProp2 == null ? null : strProp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_simprop_triggers.str_prop_3
     *
     * @return the value of public.qrtz_simprop_triggers.str_prop_3
     *
     * @mbg.generated
     */
    public String getStrProp3() {
        return strProp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_simprop_triggers.str_prop_3
     *
     * @param strProp3 the value for public.qrtz_simprop_triggers.str_prop_3
     *
     * @mbg.generated
     */
    public void setStrProp3(String strProp3) {
        this.strProp3 = strProp3 == null ? null : strProp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_simprop_triggers.int_prop_1
     *
     * @return the value of public.qrtz_simprop_triggers.int_prop_1
     *
     * @mbg.generated
     */
    public Integer getIntProp1() {
        return intProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_simprop_triggers.int_prop_1
     *
     * @param intProp1 the value for public.qrtz_simprop_triggers.int_prop_1
     *
     * @mbg.generated
     */
    public void setIntProp1(Integer intProp1) {
        this.intProp1 = intProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_simprop_triggers.int_prop_2
     *
     * @return the value of public.qrtz_simprop_triggers.int_prop_2
     *
     * @mbg.generated
     */
    public Integer getIntProp2() {
        return intProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_simprop_triggers.int_prop_2
     *
     * @param intProp2 the value for public.qrtz_simprop_triggers.int_prop_2
     *
     * @mbg.generated
     */
    public void setIntProp2(Integer intProp2) {
        this.intProp2 = intProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_simprop_triggers.long_prop_1
     *
     * @return the value of public.qrtz_simprop_triggers.long_prop_1
     *
     * @mbg.generated
     */
    public Long getLongProp1() {
        return longProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_simprop_triggers.long_prop_1
     *
     * @param longProp1 the value for public.qrtz_simprop_triggers.long_prop_1
     *
     * @mbg.generated
     */
    public void setLongProp1(Long longProp1) {
        this.longProp1 = longProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_simprop_triggers.long_prop_2
     *
     * @return the value of public.qrtz_simprop_triggers.long_prop_2
     *
     * @mbg.generated
     */
    public Long getLongProp2() {
        return longProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_simprop_triggers.long_prop_2
     *
     * @param longProp2 the value for public.qrtz_simprop_triggers.long_prop_2
     *
     * @mbg.generated
     */
    public void setLongProp2(Long longProp2) {
        this.longProp2 = longProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_simprop_triggers.dec_prop_1
     *
     * @return the value of public.qrtz_simprop_triggers.dec_prop_1
     *
     * @mbg.generated
     */
    public BigDecimal getDecProp1() {
        return decProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_simprop_triggers.dec_prop_1
     *
     * @param decProp1 the value for public.qrtz_simprop_triggers.dec_prop_1
     *
     * @mbg.generated
     */
    public void setDecProp1(BigDecimal decProp1) {
        this.decProp1 = decProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_simprop_triggers.dec_prop_2
     *
     * @return the value of public.qrtz_simprop_triggers.dec_prop_2
     *
     * @mbg.generated
     */
    public BigDecimal getDecProp2() {
        return decProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_simprop_triggers.dec_prop_2
     *
     * @param decProp2 the value for public.qrtz_simprop_triggers.dec_prop_2
     *
     * @mbg.generated
     */
    public void setDecProp2(BigDecimal decProp2) {
        this.decProp2 = decProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_simprop_triggers.bool_prop_1
     *
     * @return the value of public.qrtz_simprop_triggers.bool_prop_1
     *
     * @mbg.generated
     */
    public Boolean getBoolProp1() {
        return boolProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_simprop_triggers.bool_prop_1
     *
     * @param boolProp1 the value for public.qrtz_simprop_triggers.bool_prop_1
     *
     * @mbg.generated
     */
    public void setBoolProp1(Boolean boolProp1) {
        this.boolProp1 = boolProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_simprop_triggers.bool_prop_2
     *
     * @return the value of public.qrtz_simprop_triggers.bool_prop_2
     *
     * @mbg.generated
     */
    public Boolean getBoolProp2() {
        return boolProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_simprop_triggers.bool_prop_2
     *
     * @param boolProp2 the value for public.qrtz_simprop_triggers.bool_prop_2
     *
     * @mbg.generated
     */
    public void setBoolProp2(Boolean boolProp2) {
        this.boolProp2 = boolProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_simprop_triggers
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", strProp1=").append(strProp1);
        sb.append(", strProp2=").append(strProp2);
        sb.append(", strProp3=").append(strProp3);
        sb.append(", intProp1=").append(intProp1);
        sb.append(", intProp2=").append(intProp2);
        sb.append(", longProp1=").append(longProp1);
        sb.append(", longProp2=").append(longProp2);
        sb.append(", decProp1=").append(decProp1);
        sb.append(", decProp2=").append(decProp2);
        sb.append(", boolProp1=").append(boolProp1);
        sb.append(", boolProp2=").append(boolProp2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}