package com.example.scheduler.model.autoGenerated;

import java.io.Serializable;

public class QrtzTriggers extends QrtzTriggersKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_triggers.job_name
     *
     * @mbg.generated
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_triggers.job_group
     *
     * @mbg.generated
     */
    private String jobGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_triggers.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_triggers.next_fire_time
     *
     * @mbg.generated
     */
    private Long nextFireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_triggers.prev_fire_time
     *
     * @mbg.generated
     */
    private Long prevFireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_triggers.priority
     *
     * @mbg.generated
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_triggers.trigger_state
     *
     * @mbg.generated
     */
    private String triggerState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_triggers.trigger_type
     *
     * @mbg.generated
     */
    private String triggerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_triggers.start_time
     *
     * @mbg.generated
     */
    private Long startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_triggers.end_time
     *
     * @mbg.generated
     */
    private Long endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_triggers.calendar_name
     *
     * @mbg.generated
     */
    private String calendarName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_triggers.misfire_instr
     *
     * @mbg.generated
     */
    private Short misfireInstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.qrtz_triggers.job_data
     *
     * @mbg.generated
     */
    private byte[] jobData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.qrtz_triggers
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_triggers.job_name
     *
     * @return the value of public.qrtz_triggers.job_name
     *
     * @mbg.generated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_triggers.job_name
     *
     * @param jobName the value for public.qrtz_triggers.job_name
     *
     * @mbg.generated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_triggers.job_group
     *
     * @return the value of public.qrtz_triggers.job_group
     *
     * @mbg.generated
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_triggers.job_group
     *
     * @param jobGroup the value for public.qrtz_triggers.job_group
     *
     * @mbg.generated
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_triggers.description
     *
     * @return the value of public.qrtz_triggers.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_triggers.description
     *
     * @param description the value for public.qrtz_triggers.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_triggers.next_fire_time
     *
     * @return the value of public.qrtz_triggers.next_fire_time
     *
     * @mbg.generated
     */
    public Long getNextFireTime() {
        return nextFireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_triggers.next_fire_time
     *
     * @param nextFireTime the value for public.qrtz_triggers.next_fire_time
     *
     * @mbg.generated
     */
    public void setNextFireTime(Long nextFireTime) {
        this.nextFireTime = nextFireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_triggers.prev_fire_time
     *
     * @return the value of public.qrtz_triggers.prev_fire_time
     *
     * @mbg.generated
     */
    public Long getPrevFireTime() {
        return prevFireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_triggers.prev_fire_time
     *
     * @param prevFireTime the value for public.qrtz_triggers.prev_fire_time
     *
     * @mbg.generated
     */
    public void setPrevFireTime(Long prevFireTime) {
        this.prevFireTime = prevFireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_triggers.priority
     *
     * @return the value of public.qrtz_triggers.priority
     *
     * @mbg.generated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_triggers.priority
     *
     * @param priority the value for public.qrtz_triggers.priority
     *
     * @mbg.generated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_triggers.trigger_state
     *
     * @return the value of public.qrtz_triggers.trigger_state
     *
     * @mbg.generated
     */
    public String getTriggerState() {
        return triggerState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_triggers.trigger_state
     *
     * @param triggerState the value for public.qrtz_triggers.trigger_state
     *
     * @mbg.generated
     */
    public void setTriggerState(String triggerState) {
        this.triggerState = triggerState == null ? null : triggerState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_triggers.trigger_type
     *
     * @return the value of public.qrtz_triggers.trigger_type
     *
     * @mbg.generated
     */
    public String getTriggerType() {
        return triggerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_triggers.trigger_type
     *
     * @param triggerType the value for public.qrtz_triggers.trigger_type
     *
     * @mbg.generated
     */
    public void setTriggerType(String triggerType) {
        this.triggerType = triggerType == null ? null : triggerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_triggers.start_time
     *
     * @return the value of public.qrtz_triggers.start_time
     *
     * @mbg.generated
     */
    public Long getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_triggers.start_time
     *
     * @param startTime the value for public.qrtz_triggers.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_triggers.end_time
     *
     * @return the value of public.qrtz_triggers.end_time
     *
     * @mbg.generated
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_triggers.end_time
     *
     * @param endTime the value for public.qrtz_triggers.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_triggers.calendar_name
     *
     * @return the value of public.qrtz_triggers.calendar_name
     *
     * @mbg.generated
     */
    public String getCalendarName() {
        return calendarName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_triggers.calendar_name
     *
     * @param calendarName the value for public.qrtz_triggers.calendar_name
     *
     * @mbg.generated
     */
    public void setCalendarName(String calendarName) {
        this.calendarName = calendarName == null ? null : calendarName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_triggers.misfire_instr
     *
     * @return the value of public.qrtz_triggers.misfire_instr
     *
     * @mbg.generated
     */
    public Short getMisfireInstr() {
        return misfireInstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_triggers.misfire_instr
     *
     * @param misfireInstr the value for public.qrtz_triggers.misfire_instr
     *
     * @mbg.generated
     */
    public void setMisfireInstr(Short misfireInstr) {
        this.misfireInstr = misfireInstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.qrtz_triggers.job_data
     *
     * @return the value of public.qrtz_triggers.job_data
     *
     * @mbg.generated
     */
    public byte[] getJobData() {
        return jobData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.qrtz_triggers.job_data
     *
     * @param jobData the value for public.qrtz_triggers.job_data
     *
     * @mbg.generated
     */
    public void setJobData(byte[] jobData) {
        this.jobData = jobData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_triggers
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jobName=").append(jobName);
        sb.append(", jobGroup=").append(jobGroup);
        sb.append(", description=").append(description);
        sb.append(", nextFireTime=").append(nextFireTime);
        sb.append(", prevFireTime=").append(prevFireTime);
        sb.append(", priority=").append(priority);
        sb.append(", triggerState=").append(triggerState);
        sb.append(", triggerType=").append(triggerType);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", calendarName=").append(calendarName);
        sb.append(", misfireInstr=").append(misfireInstr);
        sb.append(", jobData=").append(jobData);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}