package com.example.scheduler.model.autoGenerated;

import java.io.Serializable;
import java.util.Date;

public class TDsAlert implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_alert.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_alert.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_alert.sign
     *
     * @mbg.generated
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_alert.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_alert.alert_status
     *
     * @mbg.generated
     */
    private Integer alertStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_alert.warning_type
     *
     * @mbg.generated
     */
    private Integer warningType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_alert.log
     *
     * @mbg.generated
     */
    private String log;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_alert.alertgroup_id
     *
     * @mbg.generated
     */
    private Integer alertgroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_alert.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_alert.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_alert.project_code
     *
     * @mbg.generated
     */
    private Long projectCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_alert.process_definition_code
     *
     * @mbg.generated
     */
    private Long processDefinitionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_alert.process_instance_id
     *
     * @mbg.generated
     */
    private Integer processInstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_alert.alert_type
     *
     * @mbg.generated
     */
    private Integer alertType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.t_ds_alert
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_alert.id
     *
     * @return the value of public.t_ds_alert.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_alert.id
     *
     * @param id the value for public.t_ds_alert.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_alert.title
     *
     * @return the value of public.t_ds_alert.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_alert.title
     *
     * @param title the value for public.t_ds_alert.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_alert.sign
     *
     * @return the value of public.t_ds_alert.sign
     *
     * @mbg.generated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_alert.sign
     *
     * @param sign the value for public.t_ds_alert.sign
     *
     * @mbg.generated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_alert.content
     *
     * @return the value of public.t_ds_alert.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_alert.content
     *
     * @param content the value for public.t_ds_alert.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_alert.alert_status
     *
     * @return the value of public.t_ds_alert.alert_status
     *
     * @mbg.generated
     */
    public Integer getAlertStatus() {
        return alertStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_alert.alert_status
     *
     * @param alertStatus the value for public.t_ds_alert.alert_status
     *
     * @mbg.generated
     */
    public void setAlertStatus(Integer alertStatus) {
        this.alertStatus = alertStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_alert.warning_type
     *
     * @return the value of public.t_ds_alert.warning_type
     *
     * @mbg.generated
     */
    public Integer getWarningType() {
        return warningType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_alert.warning_type
     *
     * @param warningType the value for public.t_ds_alert.warning_type
     *
     * @mbg.generated
     */
    public void setWarningType(Integer warningType) {
        this.warningType = warningType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_alert.log
     *
     * @return the value of public.t_ds_alert.log
     *
     * @mbg.generated
     */
    public String getLog() {
        return log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_alert.log
     *
     * @param log the value for public.t_ds_alert.log
     *
     * @mbg.generated
     */
    public void setLog(String log) {
        this.log = log == null ? null : log.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_alert.alertgroup_id
     *
     * @return the value of public.t_ds_alert.alertgroup_id
     *
     * @mbg.generated
     */
    public Integer getAlertgroupId() {
        return alertgroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_alert.alertgroup_id
     *
     * @param alertgroupId the value for public.t_ds_alert.alertgroup_id
     *
     * @mbg.generated
     */
    public void setAlertgroupId(Integer alertgroupId) {
        this.alertgroupId = alertgroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_alert.create_time
     *
     * @return the value of public.t_ds_alert.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_alert.create_time
     *
     * @param createTime the value for public.t_ds_alert.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_alert.update_time
     *
     * @return the value of public.t_ds_alert.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_alert.update_time
     *
     * @param updateTime the value for public.t_ds_alert.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_alert.project_code
     *
     * @return the value of public.t_ds_alert.project_code
     *
     * @mbg.generated
     */
    public Long getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_alert.project_code
     *
     * @param projectCode the value for public.t_ds_alert.project_code
     *
     * @mbg.generated
     */
    public void setProjectCode(Long projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_alert.process_definition_code
     *
     * @return the value of public.t_ds_alert.process_definition_code
     *
     * @mbg.generated
     */
    public Long getProcessDefinitionCode() {
        return processDefinitionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_alert.process_definition_code
     *
     * @param processDefinitionCode the value for public.t_ds_alert.process_definition_code
     *
     * @mbg.generated
     */
    public void setProcessDefinitionCode(Long processDefinitionCode) {
        this.processDefinitionCode = processDefinitionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_alert.process_instance_id
     *
     * @return the value of public.t_ds_alert.process_instance_id
     *
     * @mbg.generated
     */
    public Integer getProcessInstanceId() {
        return processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_alert.process_instance_id
     *
     * @param processInstanceId the value for public.t_ds_alert.process_instance_id
     *
     * @mbg.generated
     */
    public void setProcessInstanceId(Integer processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_alert.alert_type
     *
     * @return the value of public.t_ds_alert.alert_type
     *
     * @mbg.generated
     */
    public Integer getAlertType() {
        return alertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_alert.alert_type
     *
     * @param alertType the value for public.t_ds_alert.alert_type
     *
     * @mbg.generated
     */
    public void setAlertType(Integer alertType) {
        this.alertType = alertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", sign=").append(sign);
        sb.append(", content=").append(content);
        sb.append(", alertStatus=").append(alertStatus);
        sb.append(", warningType=").append(warningType);
        sb.append(", log=").append(log);
        sb.append(", alertgroupId=").append(alertgroupId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", projectCode=").append(projectCode);
        sb.append(", processDefinitionCode=").append(processDefinitionCode);
        sb.append(", processInstanceId=").append(processInstanceId);
        sb.append(", alertType=").append(alertType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}