package com.example.scheduler.model.autoGenerated;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TDsAlertPluginInstanceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.t_ds_alert_plugin_instance
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.t_ds_alert_plugin_instance
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.t_ds_alert_plugin_instance
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert_plugin_instance
     *
     * @mbg.generated
     */
    public TDsAlertPluginInstanceExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert_plugin_instance
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert_plugin_instance
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert_plugin_instance
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert_plugin_instance
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert_plugin_instance
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert_plugin_instance
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert_plugin_instance
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert_plugin_instance
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert_plugin_instance
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert_plugin_instance
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.t_ds_alert_plugin_instance
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPluginDefineIdIsNull() {
            addCriterion("plugin_define_id is null");
            return (Criteria) this;
        }

        public Criteria andPluginDefineIdIsNotNull() {
            addCriterion("plugin_define_id is not null");
            return (Criteria) this;
        }

        public Criteria andPluginDefineIdEqualTo(Integer value) {
            addCriterion("plugin_define_id =", value, "pluginDefineId");
            return (Criteria) this;
        }

        public Criteria andPluginDefineIdNotEqualTo(Integer value) {
            addCriterion("plugin_define_id <>", value, "pluginDefineId");
            return (Criteria) this;
        }

        public Criteria andPluginDefineIdGreaterThan(Integer value) {
            addCriterion("plugin_define_id >", value, "pluginDefineId");
            return (Criteria) this;
        }

        public Criteria andPluginDefineIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("plugin_define_id >=", value, "pluginDefineId");
            return (Criteria) this;
        }

        public Criteria andPluginDefineIdLessThan(Integer value) {
            addCriterion("plugin_define_id <", value, "pluginDefineId");
            return (Criteria) this;
        }

        public Criteria andPluginDefineIdLessThanOrEqualTo(Integer value) {
            addCriterion("plugin_define_id <=", value, "pluginDefineId");
            return (Criteria) this;
        }

        public Criteria andPluginDefineIdIn(List<Integer> values) {
            addCriterion("plugin_define_id in", values, "pluginDefineId");
            return (Criteria) this;
        }

        public Criteria andPluginDefineIdNotIn(List<Integer> values) {
            addCriterion("plugin_define_id not in", values, "pluginDefineId");
            return (Criteria) this;
        }

        public Criteria andPluginDefineIdBetween(Integer value1, Integer value2) {
            addCriterion("plugin_define_id between", value1, value2, "pluginDefineId");
            return (Criteria) this;
        }

        public Criteria andPluginDefineIdNotBetween(Integer value1, Integer value2) {
            addCriterion("plugin_define_id not between", value1, value2, "pluginDefineId");
            return (Criteria) this;
        }

        public Criteria andPluginInstanceParamsIsNull() {
            addCriterion("plugin_instance_params is null");
            return (Criteria) this;
        }

        public Criteria andPluginInstanceParamsIsNotNull() {
            addCriterion("plugin_instance_params is not null");
            return (Criteria) this;
        }

        public Criteria andPluginInstanceParamsEqualTo(String value) {
            addCriterion("plugin_instance_params =", value, "pluginInstanceParams");
            return (Criteria) this;
        }

        public Criteria andPluginInstanceParamsNotEqualTo(String value) {
            addCriterion("plugin_instance_params <>", value, "pluginInstanceParams");
            return (Criteria) this;
        }

        public Criteria andPluginInstanceParamsGreaterThan(String value) {
            addCriterion("plugin_instance_params >", value, "pluginInstanceParams");
            return (Criteria) this;
        }

        public Criteria andPluginInstanceParamsGreaterThanOrEqualTo(String value) {
            addCriterion("plugin_instance_params >=", value, "pluginInstanceParams");
            return (Criteria) this;
        }

        public Criteria andPluginInstanceParamsLessThan(String value) {
            addCriterion("plugin_instance_params <", value, "pluginInstanceParams");
            return (Criteria) this;
        }

        public Criteria andPluginInstanceParamsLessThanOrEqualTo(String value) {
            addCriterion("plugin_instance_params <=", value, "pluginInstanceParams");
            return (Criteria) this;
        }

        public Criteria andPluginInstanceParamsLike(String value) {
            addCriterion("plugin_instance_params like", value, "pluginInstanceParams");
            return (Criteria) this;
        }

        public Criteria andPluginInstanceParamsNotLike(String value) {
            addCriterion("plugin_instance_params not like", value, "pluginInstanceParams");
            return (Criteria) this;
        }

        public Criteria andPluginInstanceParamsIn(List<String> values) {
            addCriterion("plugin_instance_params in", values, "pluginInstanceParams");
            return (Criteria) this;
        }

        public Criteria andPluginInstanceParamsNotIn(List<String> values) {
            addCriterion("plugin_instance_params not in", values, "pluginInstanceParams");
            return (Criteria) this;
        }

        public Criteria andPluginInstanceParamsBetween(String value1, String value2) {
            addCriterion("plugin_instance_params between", value1, value2, "pluginInstanceParams");
            return (Criteria) this;
        }

        public Criteria andPluginInstanceParamsNotBetween(String value1, String value2) {
            addCriterion("plugin_instance_params not between", value1, value2, "pluginInstanceParams");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andInstanceNameIsNull() {
            addCriterion("instance_name is null");
            return (Criteria) this;
        }

        public Criteria andInstanceNameIsNotNull() {
            addCriterion("instance_name is not null");
            return (Criteria) this;
        }

        public Criteria andInstanceNameEqualTo(String value) {
            addCriterion("instance_name =", value, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameNotEqualTo(String value) {
            addCriterion("instance_name <>", value, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameGreaterThan(String value) {
            addCriterion("instance_name >", value, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameGreaterThanOrEqualTo(String value) {
            addCriterion("instance_name >=", value, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameLessThan(String value) {
            addCriterion("instance_name <", value, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameLessThanOrEqualTo(String value) {
            addCriterion("instance_name <=", value, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameLike(String value) {
            addCriterion("instance_name like", value, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameNotLike(String value) {
            addCriterion("instance_name not like", value, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameIn(List<String> values) {
            addCriterion("instance_name in", values, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameNotIn(List<String> values) {
            addCriterion("instance_name not in", values, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameBetween(String value1, String value2) {
            addCriterion("instance_name between", value1, value2, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameNotBetween(String value1, String value2) {
            addCriterion("instance_name not between", value1, value2, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceTypeIsNull() {
            addCriterion("instance_type is null");
            return (Criteria) this;
        }

        public Criteria andInstanceTypeIsNotNull() {
            addCriterion("instance_type is not null");
            return (Criteria) this;
        }

        public Criteria andInstanceTypeEqualTo(Integer value) {
            addCriterion("instance_type =", value, "instanceType");
            return (Criteria) this;
        }

        public Criteria andInstanceTypeNotEqualTo(Integer value) {
            addCriterion("instance_type <>", value, "instanceType");
            return (Criteria) this;
        }

        public Criteria andInstanceTypeGreaterThan(Integer value) {
            addCriterion("instance_type >", value, "instanceType");
            return (Criteria) this;
        }

        public Criteria andInstanceTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("instance_type >=", value, "instanceType");
            return (Criteria) this;
        }

        public Criteria andInstanceTypeLessThan(Integer value) {
            addCriterion("instance_type <", value, "instanceType");
            return (Criteria) this;
        }

        public Criteria andInstanceTypeLessThanOrEqualTo(Integer value) {
            addCriterion("instance_type <=", value, "instanceType");
            return (Criteria) this;
        }

        public Criteria andInstanceTypeIn(List<Integer> values) {
            addCriterion("instance_type in", values, "instanceType");
            return (Criteria) this;
        }

        public Criteria andInstanceTypeNotIn(List<Integer> values) {
            addCriterion("instance_type not in", values, "instanceType");
            return (Criteria) this;
        }

        public Criteria andInstanceTypeBetween(Integer value1, Integer value2) {
            addCriterion("instance_type between", value1, value2, "instanceType");
            return (Criteria) this;
        }

        public Criteria andInstanceTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("instance_type not between", value1, value2, "instanceType");
            return (Criteria) this;
        }

        public Criteria andWarningTypeIsNull() {
            addCriterion("warning_type is null");
            return (Criteria) this;
        }

        public Criteria andWarningTypeIsNotNull() {
            addCriterion("warning_type is not null");
            return (Criteria) this;
        }

        public Criteria andWarningTypeEqualTo(Integer value) {
            addCriterion("warning_type =", value, "warningType");
            return (Criteria) this;
        }

        public Criteria andWarningTypeNotEqualTo(Integer value) {
            addCriterion("warning_type <>", value, "warningType");
            return (Criteria) this;
        }

        public Criteria andWarningTypeGreaterThan(Integer value) {
            addCriterion("warning_type >", value, "warningType");
            return (Criteria) this;
        }

        public Criteria andWarningTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("warning_type >=", value, "warningType");
            return (Criteria) this;
        }

        public Criteria andWarningTypeLessThan(Integer value) {
            addCriterion("warning_type <", value, "warningType");
            return (Criteria) this;
        }

        public Criteria andWarningTypeLessThanOrEqualTo(Integer value) {
            addCriterion("warning_type <=", value, "warningType");
            return (Criteria) this;
        }

        public Criteria andWarningTypeIn(List<Integer> values) {
            addCriterion("warning_type in", values, "warningType");
            return (Criteria) this;
        }

        public Criteria andWarningTypeNotIn(List<Integer> values) {
            addCriterion("warning_type not in", values, "warningType");
            return (Criteria) this;
        }

        public Criteria andWarningTypeBetween(Integer value1, Integer value2) {
            addCriterion("warning_type between", value1, value2, "warningType");
            return (Criteria) this;
        }

        public Criteria andWarningTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("warning_type not between", value1, value2, "warningType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.t_ds_alert_plugin_instance
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.t_ds_alert_plugin_instance
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}