package com.example.scheduler.model.autoGenerated;

import java.io.Serializable;
import java.util.Date;

public class TDsDqTaskStatisticsValue implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_task_statistics_value.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_task_statistics_value.process_definition_id
     *
     * @mbg.generated
     */
    private Integer processDefinitionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_task_statistics_value.task_instance_id
     *
     * @mbg.generated
     */
    private Integer taskInstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_task_statistics_value.rule_id
     *
     * @mbg.generated
     */
    private Integer ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_task_statistics_value.unique_code
     *
     * @mbg.generated
     */
    private String uniqueCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_task_statistics_value.statistics_name
     *
     * @mbg.generated
     */
    private String statisticsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_task_statistics_value.statistics_value
     *
     * @mbg.generated
     */
    private Double statisticsValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_task_statistics_value.data_time
     *
     * @mbg.generated
     */
    private Date dataTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_task_statistics_value.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_task_statistics_value.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.t_ds_dq_task_statistics_value
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_task_statistics_value.id
     *
     * @return the value of public.t_ds_dq_task_statistics_value.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_task_statistics_value.id
     *
     * @param id the value for public.t_ds_dq_task_statistics_value.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_task_statistics_value.process_definition_id
     *
     * @return the value of public.t_ds_dq_task_statistics_value.process_definition_id
     *
     * @mbg.generated
     */
    public Integer getProcessDefinitionId() {
        return processDefinitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_task_statistics_value.process_definition_id
     *
     * @param processDefinitionId the value for public.t_ds_dq_task_statistics_value.process_definition_id
     *
     * @mbg.generated
     */
    public void setProcessDefinitionId(Integer processDefinitionId) {
        this.processDefinitionId = processDefinitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_task_statistics_value.task_instance_id
     *
     * @return the value of public.t_ds_dq_task_statistics_value.task_instance_id
     *
     * @mbg.generated
     */
    public Integer getTaskInstanceId() {
        return taskInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_task_statistics_value.task_instance_id
     *
     * @param taskInstanceId the value for public.t_ds_dq_task_statistics_value.task_instance_id
     *
     * @mbg.generated
     */
    public void setTaskInstanceId(Integer taskInstanceId) {
        this.taskInstanceId = taskInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_task_statistics_value.rule_id
     *
     * @return the value of public.t_ds_dq_task_statistics_value.rule_id
     *
     * @mbg.generated
     */
    public Integer getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_task_statistics_value.rule_id
     *
     * @param ruleId the value for public.t_ds_dq_task_statistics_value.rule_id
     *
     * @mbg.generated
     */
    public void setRuleId(Integer ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_task_statistics_value.unique_code
     *
     * @return the value of public.t_ds_dq_task_statistics_value.unique_code
     *
     * @mbg.generated
     */
    public String getUniqueCode() {
        return uniqueCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_task_statistics_value.unique_code
     *
     * @param uniqueCode the value for public.t_ds_dq_task_statistics_value.unique_code
     *
     * @mbg.generated
     */
    public void setUniqueCode(String uniqueCode) {
        this.uniqueCode = uniqueCode == null ? null : uniqueCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_task_statistics_value.statistics_name
     *
     * @return the value of public.t_ds_dq_task_statistics_value.statistics_name
     *
     * @mbg.generated
     */
    public String getStatisticsName() {
        return statisticsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_task_statistics_value.statistics_name
     *
     * @param statisticsName the value for public.t_ds_dq_task_statistics_value.statistics_name
     *
     * @mbg.generated
     */
    public void setStatisticsName(String statisticsName) {
        this.statisticsName = statisticsName == null ? null : statisticsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_task_statistics_value.statistics_value
     *
     * @return the value of public.t_ds_dq_task_statistics_value.statistics_value
     *
     * @mbg.generated
     */
    public Double getStatisticsValue() {
        return statisticsValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_task_statistics_value.statistics_value
     *
     * @param statisticsValue the value for public.t_ds_dq_task_statistics_value.statistics_value
     *
     * @mbg.generated
     */
    public void setStatisticsValue(Double statisticsValue) {
        this.statisticsValue = statisticsValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_task_statistics_value.data_time
     *
     * @return the value of public.t_ds_dq_task_statistics_value.data_time
     *
     * @mbg.generated
     */
    public Date getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_task_statistics_value.data_time
     *
     * @param dataTime the value for public.t_ds_dq_task_statistics_value.data_time
     *
     * @mbg.generated
     */
    public void setDataTime(Date dataTime) {
        this.dataTime = dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_task_statistics_value.create_time
     *
     * @return the value of public.t_ds_dq_task_statistics_value.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_task_statistics_value.create_time
     *
     * @param createTime the value for public.t_ds_dq_task_statistics_value.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_task_statistics_value.update_time
     *
     * @return the value of public.t_ds_dq_task_statistics_value.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_task_statistics_value.update_time
     *
     * @param updateTime the value for public.t_ds_dq_task_statistics_value.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_task_statistics_value
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", processDefinitionId=").append(processDefinitionId);
        sb.append(", taskInstanceId=").append(taskInstanceId);
        sb.append(", ruleId=").append(ruleId);
        sb.append(", uniqueCode=").append(uniqueCode);
        sb.append(", statisticsName=").append(statisticsName);
        sb.append(", statisticsValue=").append(statisticsValue);
        sb.append(", dataTime=").append(dataTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}