package com.example.scheduler.model.autoGenerated;

import java.io.Serializable;
import java.util.Date;

public class TDsDqRuleInputEntry implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_rule_input_entry.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_rule_input_entry.field
     *
     * @mbg.generated
     */
    private String field;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_rule_input_entry.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_rule_input_entry.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_rule_input_entry.data
     *
     * @mbg.generated
     */
    private String data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_rule_input_entry.options
     *
     * @mbg.generated
     */
    private String options;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_rule_input_entry.placeholder
     *
     * @mbg.generated
     */
    private String placeholder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_rule_input_entry.option_source_type
     *
     * @mbg.generated
     */
    private Integer optionSourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_rule_input_entry.data_type
     *
     * @mbg.generated
     */
    private Integer dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_rule_input_entry.input_type
     *
     * @mbg.generated
     */
    private Integer inputType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_rule_input_entry.is_show
     *
     * @mbg.generated
     */
    private Short isShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_rule_input_entry.can_edit
     *
     * @mbg.generated
     */
    private Short canEdit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_rule_input_entry.is_emit
     *
     * @mbg.generated
     */
    private Short isEmit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_rule_input_entry.is_validate
     *
     * @mbg.generated
     */
    private Short isValidate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_rule_input_entry.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_rule_input_entry.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.t_ds_dq_rule_input_entry
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_rule_input_entry.id
     *
     * @return the value of public.t_ds_dq_rule_input_entry.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_rule_input_entry.id
     *
     * @param id the value for public.t_ds_dq_rule_input_entry.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_rule_input_entry.field
     *
     * @return the value of public.t_ds_dq_rule_input_entry.field
     *
     * @mbg.generated
     */
    public String getField() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_rule_input_entry.field
     *
     * @param field the value for public.t_ds_dq_rule_input_entry.field
     *
     * @mbg.generated
     */
    public void setField(String field) {
        this.field = field == null ? null : field.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_rule_input_entry.type
     *
     * @return the value of public.t_ds_dq_rule_input_entry.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_rule_input_entry.type
     *
     * @param type the value for public.t_ds_dq_rule_input_entry.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_rule_input_entry.title
     *
     * @return the value of public.t_ds_dq_rule_input_entry.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_rule_input_entry.title
     *
     * @param title the value for public.t_ds_dq_rule_input_entry.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_rule_input_entry.data
     *
     * @return the value of public.t_ds_dq_rule_input_entry.data
     *
     * @mbg.generated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_rule_input_entry.data
     *
     * @param data the value for public.t_ds_dq_rule_input_entry.data
     *
     * @mbg.generated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_rule_input_entry.options
     *
     * @return the value of public.t_ds_dq_rule_input_entry.options
     *
     * @mbg.generated
     */
    public String getOptions() {
        return options;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_rule_input_entry.options
     *
     * @param options the value for public.t_ds_dq_rule_input_entry.options
     *
     * @mbg.generated
     */
    public void setOptions(String options) {
        this.options = options == null ? null : options.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_rule_input_entry.placeholder
     *
     * @return the value of public.t_ds_dq_rule_input_entry.placeholder
     *
     * @mbg.generated
     */
    public String getPlaceholder() {
        return placeholder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_rule_input_entry.placeholder
     *
     * @param placeholder the value for public.t_ds_dq_rule_input_entry.placeholder
     *
     * @mbg.generated
     */
    public void setPlaceholder(String placeholder) {
        this.placeholder = placeholder == null ? null : placeholder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_rule_input_entry.option_source_type
     *
     * @return the value of public.t_ds_dq_rule_input_entry.option_source_type
     *
     * @mbg.generated
     */
    public Integer getOptionSourceType() {
        return optionSourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_rule_input_entry.option_source_type
     *
     * @param optionSourceType the value for public.t_ds_dq_rule_input_entry.option_source_type
     *
     * @mbg.generated
     */
    public void setOptionSourceType(Integer optionSourceType) {
        this.optionSourceType = optionSourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_rule_input_entry.data_type
     *
     * @return the value of public.t_ds_dq_rule_input_entry.data_type
     *
     * @mbg.generated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_rule_input_entry.data_type
     *
     * @param dataType the value for public.t_ds_dq_rule_input_entry.data_type
     *
     * @mbg.generated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_rule_input_entry.input_type
     *
     * @return the value of public.t_ds_dq_rule_input_entry.input_type
     *
     * @mbg.generated
     */
    public Integer getInputType() {
        return inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_rule_input_entry.input_type
     *
     * @param inputType the value for public.t_ds_dq_rule_input_entry.input_type
     *
     * @mbg.generated
     */
    public void setInputType(Integer inputType) {
        this.inputType = inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_rule_input_entry.is_show
     *
     * @return the value of public.t_ds_dq_rule_input_entry.is_show
     *
     * @mbg.generated
     */
    public Short getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_rule_input_entry.is_show
     *
     * @param isShow the value for public.t_ds_dq_rule_input_entry.is_show
     *
     * @mbg.generated
     */
    public void setIsShow(Short isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_rule_input_entry.can_edit
     *
     * @return the value of public.t_ds_dq_rule_input_entry.can_edit
     *
     * @mbg.generated
     */
    public Short getCanEdit() {
        return canEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_rule_input_entry.can_edit
     *
     * @param canEdit the value for public.t_ds_dq_rule_input_entry.can_edit
     *
     * @mbg.generated
     */
    public void setCanEdit(Short canEdit) {
        this.canEdit = canEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_rule_input_entry.is_emit
     *
     * @return the value of public.t_ds_dq_rule_input_entry.is_emit
     *
     * @mbg.generated
     */
    public Short getIsEmit() {
        return isEmit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_rule_input_entry.is_emit
     *
     * @param isEmit the value for public.t_ds_dq_rule_input_entry.is_emit
     *
     * @mbg.generated
     */
    public void setIsEmit(Short isEmit) {
        this.isEmit = isEmit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_rule_input_entry.is_validate
     *
     * @return the value of public.t_ds_dq_rule_input_entry.is_validate
     *
     * @mbg.generated
     */
    public Short getIsValidate() {
        return isValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_rule_input_entry.is_validate
     *
     * @param isValidate the value for public.t_ds_dq_rule_input_entry.is_validate
     *
     * @mbg.generated
     */
    public void setIsValidate(Short isValidate) {
        this.isValidate = isValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_rule_input_entry.create_time
     *
     * @return the value of public.t_ds_dq_rule_input_entry.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_rule_input_entry.create_time
     *
     * @param createTime the value for public.t_ds_dq_rule_input_entry.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_rule_input_entry.update_time
     *
     * @return the value of public.t_ds_dq_rule_input_entry.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_rule_input_entry.update_time
     *
     * @param updateTime the value for public.t_ds_dq_rule_input_entry.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_rule_input_entry
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", field=").append(field);
        sb.append(", type=").append(type);
        sb.append(", title=").append(title);
        sb.append(", data=").append(data);
        sb.append(", options=").append(options);
        sb.append(", placeholder=").append(placeholder);
        sb.append(", optionSourceType=").append(optionSourceType);
        sb.append(", dataType=").append(dataType);
        sb.append(", inputType=").append(inputType);
        sb.append(", isShow=").append(isShow);
        sb.append(", canEdit=").append(canEdit);
        sb.append(", isEmit=").append(isEmit);
        sb.append(", isValidate=").append(isValidate);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}