package com.example.scheduler.model.autoGenerated;

import java.io.Serializable;
import java.util.Date;

public class TDsDqComparisonType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_comparison_type.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_comparison_type.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_comparison_type.execute_sql
     *
     * @mbg.generated
     */
    private String executeSql;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_comparison_type.output_table
     *
     * @mbg.generated
     */
    private String outputTable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_comparison_type.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_comparison_type.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_comparison_type.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_dq_comparison_type.is_inner_source
     *
     * @mbg.generated
     */
    private Boolean isInnerSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.t_ds_dq_comparison_type
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_comparison_type.id
     *
     * @return the value of public.t_ds_dq_comparison_type.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_comparison_type.id
     *
     * @param id the value for public.t_ds_dq_comparison_type.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_comparison_type.type
     *
     * @return the value of public.t_ds_dq_comparison_type.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_comparison_type.type
     *
     * @param type the value for public.t_ds_dq_comparison_type.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_comparison_type.execute_sql
     *
     * @return the value of public.t_ds_dq_comparison_type.execute_sql
     *
     * @mbg.generated
     */
    public String getExecuteSql() {
        return executeSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_comparison_type.execute_sql
     *
     * @param executeSql the value for public.t_ds_dq_comparison_type.execute_sql
     *
     * @mbg.generated
     */
    public void setExecuteSql(String executeSql) {
        this.executeSql = executeSql == null ? null : executeSql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_comparison_type.output_table
     *
     * @return the value of public.t_ds_dq_comparison_type.output_table
     *
     * @mbg.generated
     */
    public String getOutputTable() {
        return outputTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_comparison_type.output_table
     *
     * @param outputTable the value for public.t_ds_dq_comparison_type.output_table
     *
     * @mbg.generated
     */
    public void setOutputTable(String outputTable) {
        this.outputTable = outputTable == null ? null : outputTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_comparison_type.name
     *
     * @return the value of public.t_ds_dq_comparison_type.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_comparison_type.name
     *
     * @param name the value for public.t_ds_dq_comparison_type.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_comparison_type.create_time
     *
     * @return the value of public.t_ds_dq_comparison_type.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_comparison_type.create_time
     *
     * @param createTime the value for public.t_ds_dq_comparison_type.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_comparison_type.update_time
     *
     * @return the value of public.t_ds_dq_comparison_type.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_comparison_type.update_time
     *
     * @param updateTime the value for public.t_ds_dq_comparison_type.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_dq_comparison_type.is_inner_source
     *
     * @return the value of public.t_ds_dq_comparison_type.is_inner_source
     *
     * @mbg.generated
     */
    public Boolean getIsInnerSource() {
        return isInnerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_dq_comparison_type.is_inner_source
     *
     * @param isInnerSource the value for public.t_ds_dq_comparison_type.is_inner_source
     *
     * @mbg.generated
     */
    public void setIsInnerSource(Boolean isInnerSource) {
        this.isInnerSource = isInnerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_comparison_type
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", executeSql=").append(executeSql);
        sb.append(", outputTable=").append(outputTable);
        sb.append(", name=").append(name);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", isInnerSource=").append(isInnerSource);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}