package com.example.scheduler.model.autoGenerated;

import java.io.Serializable;
import java.util.Date;

public class TDsEnvironmentWorkerGroupRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_environment_worker_group_relation.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_environment_worker_group_relation.environment_code
     *
     * @mbg.generated
     */
    private Long environmentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_environment_worker_group_relation.worker_group
     *
     * @mbg.generated
     */
    private String workerGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_environment_worker_group_relation.operator
     *
     * @mbg.generated
     */
    private Integer operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_environment_worker_group_relation.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_environment_worker_group_relation.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.t_ds_environment_worker_group_relation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_environment_worker_group_relation.id
     *
     * @return the value of public.t_ds_environment_worker_group_relation.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_environment_worker_group_relation.id
     *
     * @param id the value for public.t_ds_environment_worker_group_relation.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_environment_worker_group_relation.environment_code
     *
     * @return the value of public.t_ds_environment_worker_group_relation.environment_code
     *
     * @mbg.generated
     */
    public Long getEnvironmentCode() {
        return environmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_environment_worker_group_relation.environment_code
     *
     * @param environmentCode the value for public.t_ds_environment_worker_group_relation.environment_code
     *
     * @mbg.generated
     */
    public void setEnvironmentCode(Long environmentCode) {
        this.environmentCode = environmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_environment_worker_group_relation.worker_group
     *
     * @return the value of public.t_ds_environment_worker_group_relation.worker_group
     *
     * @mbg.generated
     */
    public String getWorkerGroup() {
        return workerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_environment_worker_group_relation.worker_group
     *
     * @param workerGroup the value for public.t_ds_environment_worker_group_relation.worker_group
     *
     * @mbg.generated
     */
    public void setWorkerGroup(String workerGroup) {
        this.workerGroup = workerGroup == null ? null : workerGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_environment_worker_group_relation.operator
     *
     * @return the value of public.t_ds_environment_worker_group_relation.operator
     *
     * @mbg.generated
     */
    public Integer getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_environment_worker_group_relation.operator
     *
     * @param operator the value for public.t_ds_environment_worker_group_relation.operator
     *
     * @mbg.generated
     */
    public void setOperator(Integer operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_environment_worker_group_relation.create_time
     *
     * @return the value of public.t_ds_environment_worker_group_relation.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_environment_worker_group_relation.create_time
     *
     * @param createTime the value for public.t_ds_environment_worker_group_relation.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_environment_worker_group_relation.update_time
     *
     * @return the value of public.t_ds_environment_worker_group_relation.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_environment_worker_group_relation.update_time
     *
     * @param updateTime the value for public.t_ds_environment_worker_group_relation.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_environment_worker_group_relation
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", environmentCode=").append(environmentCode);
        sb.append(", workerGroup=").append(workerGroup);
        sb.append(", operator=").append(operator);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}