package com.example.scheduler.model.autoGenerated;

import java.io.Serializable;
import java.util.Date;

public class TDsListenerEvent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_listener_event.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_listener_event.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_listener_event.sign
     *
     * @mbg.generated
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_listener_event.post_status
     *
     * @mbg.generated
     */
    private Integer postStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_listener_event.event_type
     *
     * @mbg.generated
     */
    private Integer eventType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_listener_event.log
     *
     * @mbg.generated
     */
    private String log;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_listener_event.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_listener_event.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.t_ds_listener_event
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_listener_event.id
     *
     * @return the value of public.t_ds_listener_event.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_listener_event.id
     *
     * @param id the value for public.t_ds_listener_event.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_listener_event.content
     *
     * @return the value of public.t_ds_listener_event.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_listener_event.content
     *
     * @param content the value for public.t_ds_listener_event.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_listener_event.sign
     *
     * @return the value of public.t_ds_listener_event.sign
     *
     * @mbg.generated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_listener_event.sign
     *
     * @param sign the value for public.t_ds_listener_event.sign
     *
     * @mbg.generated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_listener_event.post_status
     *
     * @return the value of public.t_ds_listener_event.post_status
     *
     * @mbg.generated
     */
    public Integer getPostStatus() {
        return postStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_listener_event.post_status
     *
     * @param postStatus the value for public.t_ds_listener_event.post_status
     *
     * @mbg.generated
     */
    public void setPostStatus(Integer postStatus) {
        this.postStatus = postStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_listener_event.event_type
     *
     * @return the value of public.t_ds_listener_event.event_type
     *
     * @mbg.generated
     */
    public Integer getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_listener_event.event_type
     *
     * @param eventType the value for public.t_ds_listener_event.event_type
     *
     * @mbg.generated
     */
    public void setEventType(Integer eventType) {
        this.eventType = eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_listener_event.log
     *
     * @return the value of public.t_ds_listener_event.log
     *
     * @mbg.generated
     */
    public String getLog() {
        return log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_listener_event.log
     *
     * @param log the value for public.t_ds_listener_event.log
     *
     * @mbg.generated
     */
    public void setLog(String log) {
        this.log = log == null ? null : log.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_listener_event.create_time
     *
     * @return the value of public.t_ds_listener_event.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_listener_event.create_time
     *
     * @param createTime the value for public.t_ds_listener_event.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_listener_event.update_time
     *
     * @return the value of public.t_ds_listener_event.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_listener_event.update_time
     *
     * @param updateTime the value for public.t_ds_listener_event.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_listener_event
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", content=").append(content);
        sb.append(", sign=").append(sign);
        sb.append(", postStatus=").append(postStatus);
        sb.append(", eventType=").append(eventType);
        sb.append(", log=").append(log);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}