package com.example.scheduler.model.autoGenerated;

import java.io.Serializable;
import java.util.Date;

public class TDsPluginDefine implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_plugin_define.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_plugin_define.plugin_name
     *
     * @mbg.generated
     */
    private String pluginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_plugin_define.plugin_type
     *
     * @mbg.generated
     */
    private String pluginType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_plugin_define.plugin_params
     *
     * @mbg.generated
     */
    private String pluginParams;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_plugin_define.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_plugin_define.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.t_ds_plugin_define
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_plugin_define.id
     *
     * @return the value of public.t_ds_plugin_define.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_plugin_define.id
     *
     * @param id the value for public.t_ds_plugin_define.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_plugin_define.plugin_name
     *
     * @return the value of public.t_ds_plugin_define.plugin_name
     *
     * @mbg.generated
     */
    public String getPluginName() {
        return pluginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_plugin_define.plugin_name
     *
     * @param pluginName the value for public.t_ds_plugin_define.plugin_name
     *
     * @mbg.generated
     */
    public void setPluginName(String pluginName) {
        this.pluginName = pluginName == null ? null : pluginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_plugin_define.plugin_type
     *
     * @return the value of public.t_ds_plugin_define.plugin_type
     *
     * @mbg.generated
     */
    public String getPluginType() {
        return pluginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_plugin_define.plugin_type
     *
     * @param pluginType the value for public.t_ds_plugin_define.plugin_type
     *
     * @mbg.generated
     */
    public void setPluginType(String pluginType) {
        this.pluginType = pluginType == null ? null : pluginType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_plugin_define.plugin_params
     *
     * @return the value of public.t_ds_plugin_define.plugin_params
     *
     * @mbg.generated
     */
    public String getPluginParams() {
        return pluginParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_plugin_define.plugin_params
     *
     * @param pluginParams the value for public.t_ds_plugin_define.plugin_params
     *
     * @mbg.generated
     */
    public void setPluginParams(String pluginParams) {
        this.pluginParams = pluginParams == null ? null : pluginParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_plugin_define.create_time
     *
     * @return the value of public.t_ds_plugin_define.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_plugin_define.create_time
     *
     * @param createTime the value for public.t_ds_plugin_define.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_plugin_define.update_time
     *
     * @return the value of public.t_ds_plugin_define.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_plugin_define.update_time
     *
     * @param updateTime the value for public.t_ds_plugin_define.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_plugin_define
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pluginName=").append(pluginName);
        sb.append(", pluginType=").append(pluginType);
        sb.append(", pluginParams=").append(pluginParams);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}