package com.example.scheduler.model.autoGenerated;

import java.io.Serializable;
import java.util.Date;

public class TDsProcessInstance implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.process_definition_code
     *
     * @mbg.generated
     */
    private Long processDefinitionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.process_definition_version
     *
     * @mbg.generated
     */
    private Integer processDefinitionVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.project_code
     *
     * @mbg.generated
     */
    private Long projectCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.state_history
     *
     * @mbg.generated
     */
    private String stateHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.recovery
     *
     * @mbg.generated
     */
    private Integer recovery;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.run_times
     *
     * @mbg.generated
     */
    private Integer runTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.host
     *
     * @mbg.generated
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.command_type
     *
     * @mbg.generated
     */
    private Integer commandType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.command_param
     *
     * @mbg.generated
     */
    private String commandParam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.task_depend_type
     *
     * @mbg.generated
     */
    private Integer taskDependType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.max_try_times
     *
     * @mbg.generated
     */
    private Integer maxTryTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.failure_strategy
     *
     * @mbg.generated
     */
    private Integer failureStrategy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.warning_type
     *
     * @mbg.generated
     */
    private Integer warningType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.warning_group_id
     *
     * @mbg.generated
     */
    private Integer warningGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.schedule_time
     *
     * @mbg.generated
     */
    private Date scheduleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.command_start_time
     *
     * @mbg.generated
     */
    private Date commandStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.global_params
     *
     * @mbg.generated
     */
    private String globalParams;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.process_instance_json
     *
     * @mbg.generated
     */
    private String processInstanceJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.flag
     *
     * @mbg.generated
     */
    private Integer flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.is_sub_process
     *
     * @mbg.generated
     */
    private Integer isSubProcess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.executor_id
     *
     * @mbg.generated
     */
    private Integer executorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.executor_name
     *
     * @mbg.generated
     */
    private String executorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.history_cmd
     *
     * @mbg.generated
     */
    private String historyCmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.dependence_schedule_times
     *
     * @mbg.generated
     */
    private String dependenceScheduleTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.process_instance_priority
     *
     * @mbg.generated
     */
    private Integer processInstancePriority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.worker_group
     *
     * @mbg.generated
     */
    private String workerGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.environment_code
     *
     * @mbg.generated
     */
    private Long environmentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.timeout
     *
     * @mbg.generated
     */
    private Integer timeout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.tenant_code
     *
     * @mbg.generated
     */
    private String tenantCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.var_pool
     *
     * @mbg.generated
     */
    private String varPool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.dry_run
     *
     * @mbg.generated
     */
    private Integer dryRun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.next_process_instance_id
     *
     * @mbg.generated
     */
    private Integer nextProcessInstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.restart_time
     *
     * @mbg.generated
     */
    private Date restartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_process_instance.test_flag
     *
     * @mbg.generated
     */
    private Integer testFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.t_ds_process_instance
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.id
     *
     * @return the value of public.t_ds_process_instance.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.id
     *
     * @param id the value for public.t_ds_process_instance.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.name
     *
     * @return the value of public.t_ds_process_instance.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.name
     *
     * @param name the value for public.t_ds_process_instance.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.process_definition_code
     *
     * @return the value of public.t_ds_process_instance.process_definition_code
     *
     * @mbg.generated
     */
    public Long getProcessDefinitionCode() {
        return processDefinitionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.process_definition_code
     *
     * @param processDefinitionCode the value for public.t_ds_process_instance.process_definition_code
     *
     * @mbg.generated
     */
    public void setProcessDefinitionCode(Long processDefinitionCode) {
        this.processDefinitionCode = processDefinitionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.process_definition_version
     *
     * @return the value of public.t_ds_process_instance.process_definition_version
     *
     * @mbg.generated
     */
    public Integer getProcessDefinitionVersion() {
        return processDefinitionVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.process_definition_version
     *
     * @param processDefinitionVersion the value for public.t_ds_process_instance.process_definition_version
     *
     * @mbg.generated
     */
    public void setProcessDefinitionVersion(Integer processDefinitionVersion) {
        this.processDefinitionVersion = processDefinitionVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.project_code
     *
     * @return the value of public.t_ds_process_instance.project_code
     *
     * @mbg.generated
     */
    public Long getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.project_code
     *
     * @param projectCode the value for public.t_ds_process_instance.project_code
     *
     * @mbg.generated
     */
    public void setProjectCode(Long projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.state
     *
     * @return the value of public.t_ds_process_instance.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.state
     *
     * @param state the value for public.t_ds_process_instance.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.state_history
     *
     * @return the value of public.t_ds_process_instance.state_history
     *
     * @mbg.generated
     */
    public String getStateHistory() {
        return stateHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.state_history
     *
     * @param stateHistory the value for public.t_ds_process_instance.state_history
     *
     * @mbg.generated
     */
    public void setStateHistory(String stateHistory) {
        this.stateHistory = stateHistory == null ? null : stateHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.recovery
     *
     * @return the value of public.t_ds_process_instance.recovery
     *
     * @mbg.generated
     */
    public Integer getRecovery() {
        return recovery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.recovery
     *
     * @param recovery the value for public.t_ds_process_instance.recovery
     *
     * @mbg.generated
     */
    public void setRecovery(Integer recovery) {
        this.recovery = recovery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.start_time
     *
     * @return the value of public.t_ds_process_instance.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.start_time
     *
     * @param startTime the value for public.t_ds_process_instance.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.end_time
     *
     * @return the value of public.t_ds_process_instance.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.end_time
     *
     * @param endTime the value for public.t_ds_process_instance.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.run_times
     *
     * @return the value of public.t_ds_process_instance.run_times
     *
     * @mbg.generated
     */
    public Integer getRunTimes() {
        return runTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.run_times
     *
     * @param runTimes the value for public.t_ds_process_instance.run_times
     *
     * @mbg.generated
     */
    public void setRunTimes(Integer runTimes) {
        this.runTimes = runTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.host
     *
     * @return the value of public.t_ds_process_instance.host
     *
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.host
     *
     * @param host the value for public.t_ds_process_instance.host
     *
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.command_type
     *
     * @return the value of public.t_ds_process_instance.command_type
     *
     * @mbg.generated
     */
    public Integer getCommandType() {
        return commandType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.command_type
     *
     * @param commandType the value for public.t_ds_process_instance.command_type
     *
     * @mbg.generated
     */
    public void setCommandType(Integer commandType) {
        this.commandType = commandType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.command_param
     *
     * @return the value of public.t_ds_process_instance.command_param
     *
     * @mbg.generated
     */
    public String getCommandParam() {
        return commandParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.command_param
     *
     * @param commandParam the value for public.t_ds_process_instance.command_param
     *
     * @mbg.generated
     */
    public void setCommandParam(String commandParam) {
        this.commandParam = commandParam == null ? null : commandParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.task_depend_type
     *
     * @return the value of public.t_ds_process_instance.task_depend_type
     *
     * @mbg.generated
     */
    public Integer getTaskDependType() {
        return taskDependType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.task_depend_type
     *
     * @param taskDependType the value for public.t_ds_process_instance.task_depend_type
     *
     * @mbg.generated
     */
    public void setTaskDependType(Integer taskDependType) {
        this.taskDependType = taskDependType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.max_try_times
     *
     * @return the value of public.t_ds_process_instance.max_try_times
     *
     * @mbg.generated
     */
    public Integer getMaxTryTimes() {
        return maxTryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.max_try_times
     *
     * @param maxTryTimes the value for public.t_ds_process_instance.max_try_times
     *
     * @mbg.generated
     */
    public void setMaxTryTimes(Integer maxTryTimes) {
        this.maxTryTimes = maxTryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.failure_strategy
     *
     * @return the value of public.t_ds_process_instance.failure_strategy
     *
     * @mbg.generated
     */
    public Integer getFailureStrategy() {
        return failureStrategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.failure_strategy
     *
     * @param failureStrategy the value for public.t_ds_process_instance.failure_strategy
     *
     * @mbg.generated
     */
    public void setFailureStrategy(Integer failureStrategy) {
        this.failureStrategy = failureStrategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.warning_type
     *
     * @return the value of public.t_ds_process_instance.warning_type
     *
     * @mbg.generated
     */
    public Integer getWarningType() {
        return warningType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.warning_type
     *
     * @param warningType the value for public.t_ds_process_instance.warning_type
     *
     * @mbg.generated
     */
    public void setWarningType(Integer warningType) {
        this.warningType = warningType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.warning_group_id
     *
     * @return the value of public.t_ds_process_instance.warning_group_id
     *
     * @mbg.generated
     */
    public Integer getWarningGroupId() {
        return warningGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.warning_group_id
     *
     * @param warningGroupId the value for public.t_ds_process_instance.warning_group_id
     *
     * @mbg.generated
     */
    public void setWarningGroupId(Integer warningGroupId) {
        this.warningGroupId = warningGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.schedule_time
     *
     * @return the value of public.t_ds_process_instance.schedule_time
     *
     * @mbg.generated
     */
    public Date getScheduleTime() {
        return scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.schedule_time
     *
     * @param scheduleTime the value for public.t_ds_process_instance.schedule_time
     *
     * @mbg.generated
     */
    public void setScheduleTime(Date scheduleTime) {
        this.scheduleTime = scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.command_start_time
     *
     * @return the value of public.t_ds_process_instance.command_start_time
     *
     * @mbg.generated
     */
    public Date getCommandStartTime() {
        return commandStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.command_start_time
     *
     * @param commandStartTime the value for public.t_ds_process_instance.command_start_time
     *
     * @mbg.generated
     */
    public void setCommandStartTime(Date commandStartTime) {
        this.commandStartTime = commandStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.global_params
     *
     * @return the value of public.t_ds_process_instance.global_params
     *
     * @mbg.generated
     */
    public String getGlobalParams() {
        return globalParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.global_params
     *
     * @param globalParams the value for public.t_ds_process_instance.global_params
     *
     * @mbg.generated
     */
    public void setGlobalParams(String globalParams) {
        this.globalParams = globalParams == null ? null : globalParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.process_instance_json
     *
     * @return the value of public.t_ds_process_instance.process_instance_json
     *
     * @mbg.generated
     */
    public String getProcessInstanceJson() {
        return processInstanceJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.process_instance_json
     *
     * @param processInstanceJson the value for public.t_ds_process_instance.process_instance_json
     *
     * @mbg.generated
     */
    public void setProcessInstanceJson(String processInstanceJson) {
        this.processInstanceJson = processInstanceJson == null ? null : processInstanceJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.flag
     *
     * @return the value of public.t_ds_process_instance.flag
     *
     * @mbg.generated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.flag
     *
     * @param flag the value for public.t_ds_process_instance.flag
     *
     * @mbg.generated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.update_time
     *
     * @return the value of public.t_ds_process_instance.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.update_time
     *
     * @param updateTime the value for public.t_ds_process_instance.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.is_sub_process
     *
     * @return the value of public.t_ds_process_instance.is_sub_process
     *
     * @mbg.generated
     */
    public Integer getIsSubProcess() {
        return isSubProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.is_sub_process
     *
     * @param isSubProcess the value for public.t_ds_process_instance.is_sub_process
     *
     * @mbg.generated
     */
    public void setIsSubProcess(Integer isSubProcess) {
        this.isSubProcess = isSubProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.executor_id
     *
     * @return the value of public.t_ds_process_instance.executor_id
     *
     * @mbg.generated
     */
    public Integer getExecutorId() {
        return executorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.executor_id
     *
     * @param executorId the value for public.t_ds_process_instance.executor_id
     *
     * @mbg.generated
     */
    public void setExecutorId(Integer executorId) {
        this.executorId = executorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.executor_name
     *
     * @return the value of public.t_ds_process_instance.executor_name
     *
     * @mbg.generated
     */
    public String getExecutorName() {
        return executorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.executor_name
     *
     * @param executorName the value for public.t_ds_process_instance.executor_name
     *
     * @mbg.generated
     */
    public void setExecutorName(String executorName) {
        this.executorName = executorName == null ? null : executorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.history_cmd
     *
     * @return the value of public.t_ds_process_instance.history_cmd
     *
     * @mbg.generated
     */
    public String getHistoryCmd() {
        return historyCmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.history_cmd
     *
     * @param historyCmd the value for public.t_ds_process_instance.history_cmd
     *
     * @mbg.generated
     */
    public void setHistoryCmd(String historyCmd) {
        this.historyCmd = historyCmd == null ? null : historyCmd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.dependence_schedule_times
     *
     * @return the value of public.t_ds_process_instance.dependence_schedule_times
     *
     * @mbg.generated
     */
    public String getDependenceScheduleTimes() {
        return dependenceScheduleTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.dependence_schedule_times
     *
     * @param dependenceScheduleTimes the value for public.t_ds_process_instance.dependence_schedule_times
     *
     * @mbg.generated
     */
    public void setDependenceScheduleTimes(String dependenceScheduleTimes) {
        this.dependenceScheduleTimes = dependenceScheduleTimes == null ? null : dependenceScheduleTimes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.process_instance_priority
     *
     * @return the value of public.t_ds_process_instance.process_instance_priority
     *
     * @mbg.generated
     */
    public Integer getProcessInstancePriority() {
        return processInstancePriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.process_instance_priority
     *
     * @param processInstancePriority the value for public.t_ds_process_instance.process_instance_priority
     *
     * @mbg.generated
     */
    public void setProcessInstancePriority(Integer processInstancePriority) {
        this.processInstancePriority = processInstancePriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.worker_group
     *
     * @return the value of public.t_ds_process_instance.worker_group
     *
     * @mbg.generated
     */
    public String getWorkerGroup() {
        return workerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.worker_group
     *
     * @param workerGroup the value for public.t_ds_process_instance.worker_group
     *
     * @mbg.generated
     */
    public void setWorkerGroup(String workerGroup) {
        this.workerGroup = workerGroup == null ? null : workerGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.environment_code
     *
     * @return the value of public.t_ds_process_instance.environment_code
     *
     * @mbg.generated
     */
    public Long getEnvironmentCode() {
        return environmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.environment_code
     *
     * @param environmentCode the value for public.t_ds_process_instance.environment_code
     *
     * @mbg.generated
     */
    public void setEnvironmentCode(Long environmentCode) {
        this.environmentCode = environmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.timeout
     *
     * @return the value of public.t_ds_process_instance.timeout
     *
     * @mbg.generated
     */
    public Integer getTimeout() {
        return timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.timeout
     *
     * @param timeout the value for public.t_ds_process_instance.timeout
     *
     * @mbg.generated
     */
    public void setTimeout(Integer timeout) {
        this.timeout = timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.tenant_code
     *
     * @return the value of public.t_ds_process_instance.tenant_code
     *
     * @mbg.generated
     */
    public String getTenantCode() {
        return tenantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.tenant_code
     *
     * @param tenantCode the value for public.t_ds_process_instance.tenant_code
     *
     * @mbg.generated
     */
    public void setTenantCode(String tenantCode) {
        this.tenantCode = tenantCode == null ? null : tenantCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.var_pool
     *
     * @return the value of public.t_ds_process_instance.var_pool
     *
     * @mbg.generated
     */
    public String getVarPool() {
        return varPool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.var_pool
     *
     * @param varPool the value for public.t_ds_process_instance.var_pool
     *
     * @mbg.generated
     */
    public void setVarPool(String varPool) {
        this.varPool = varPool == null ? null : varPool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.dry_run
     *
     * @return the value of public.t_ds_process_instance.dry_run
     *
     * @mbg.generated
     */
    public Integer getDryRun() {
        return dryRun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.dry_run
     *
     * @param dryRun the value for public.t_ds_process_instance.dry_run
     *
     * @mbg.generated
     */
    public void setDryRun(Integer dryRun) {
        this.dryRun = dryRun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.next_process_instance_id
     *
     * @return the value of public.t_ds_process_instance.next_process_instance_id
     *
     * @mbg.generated
     */
    public Integer getNextProcessInstanceId() {
        return nextProcessInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.next_process_instance_id
     *
     * @param nextProcessInstanceId the value for public.t_ds_process_instance.next_process_instance_id
     *
     * @mbg.generated
     */
    public void setNextProcessInstanceId(Integer nextProcessInstanceId) {
        this.nextProcessInstanceId = nextProcessInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.restart_time
     *
     * @return the value of public.t_ds_process_instance.restart_time
     *
     * @mbg.generated
     */
    public Date getRestartTime() {
        return restartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.restart_time
     *
     * @param restartTime the value for public.t_ds_process_instance.restart_time
     *
     * @mbg.generated
     */
    public void setRestartTime(Date restartTime) {
        this.restartTime = restartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_process_instance.test_flag
     *
     * @return the value of public.t_ds_process_instance.test_flag
     *
     * @mbg.generated
     */
    public Integer getTestFlag() {
        return testFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_process_instance.test_flag
     *
     * @param testFlag the value for public.t_ds_process_instance.test_flag
     *
     * @mbg.generated
     */
    public void setTestFlag(Integer testFlag) {
        this.testFlag = testFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_process_instance
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", processDefinitionCode=").append(processDefinitionCode);
        sb.append(", processDefinitionVersion=").append(processDefinitionVersion);
        sb.append(", projectCode=").append(projectCode);
        sb.append(", state=").append(state);
        sb.append(", stateHistory=").append(stateHistory);
        sb.append(", recovery=").append(recovery);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", runTimes=").append(runTimes);
        sb.append(", host=").append(host);
        sb.append(", commandType=").append(commandType);
        sb.append(", commandParam=").append(commandParam);
        sb.append(", taskDependType=").append(taskDependType);
        sb.append(", maxTryTimes=").append(maxTryTimes);
        sb.append(", failureStrategy=").append(failureStrategy);
        sb.append(", warningType=").append(warningType);
        sb.append(", warningGroupId=").append(warningGroupId);
        sb.append(", scheduleTime=").append(scheduleTime);
        sb.append(", commandStartTime=").append(commandStartTime);
        sb.append(", globalParams=").append(globalParams);
        sb.append(", processInstanceJson=").append(processInstanceJson);
        sb.append(", flag=").append(flag);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", isSubProcess=").append(isSubProcess);
        sb.append(", executorId=").append(executorId);
        sb.append(", executorName=").append(executorName);
        sb.append(", historyCmd=").append(historyCmd);
        sb.append(", dependenceScheduleTimes=").append(dependenceScheduleTimes);
        sb.append(", processInstancePriority=").append(processInstancePriority);
        sb.append(", workerGroup=").append(workerGroup);
        sb.append(", environmentCode=").append(environmentCode);
        sb.append(", timeout=").append(timeout);
        sb.append(", tenantCode=").append(tenantCode);
        sb.append(", varPool=").append(varPool);
        sb.append(", dryRun=").append(dryRun);
        sb.append(", nextProcessInstanceId=").append(nextProcessInstanceId);
        sb.append(", restartTime=").append(restartTime);
        sb.append(", testFlag=").append(testFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}