package com.example.scheduler.model.autoGenerated;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TDsTaskDefinitionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.t_ds_task_definition
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.t_ds_task_definition
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.t_ds_task_definition
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_definition
     *
     * @mbg.generated
     */
    public TDsTaskDefinitionExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_definition
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_definition
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_definition
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_definition
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_definition
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_definition
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_definition
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_definition
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_definition
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_definition
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.t_ds_task_definition
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(Long value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(Long value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(Long value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(Long value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(Long value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<Long> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<Long> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(Long value1, Long value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(Long value1, Long value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andProjectCodeIsNull() {
            addCriterion("project_code is null");
            return (Criteria) this;
        }

        public Criteria andProjectCodeIsNotNull() {
            addCriterion("project_code is not null");
            return (Criteria) this;
        }

        public Criteria andProjectCodeEqualTo(Long value) {
            addCriterion("project_code =", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeNotEqualTo(Long value) {
            addCriterion("project_code <>", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeGreaterThan(Long value) {
            addCriterion("project_code >", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("project_code >=", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeLessThan(Long value) {
            addCriterion("project_code <", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeLessThanOrEqualTo(Long value) {
            addCriterion("project_code <=", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeIn(List<Long> values) {
            addCriterion("project_code in", values, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeNotIn(List<Long> values) {
            addCriterion("project_code not in", values, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeBetween(Long value1, Long value2) {
            addCriterion("project_code between", value1, value2, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeNotBetween(Long value1, Long value2) {
            addCriterion("project_code not between", value1, value2, "projectCode");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andTaskTypeIsNull() {
            addCriterion("task_type is null");
            return (Criteria) this;
        }

        public Criteria andTaskTypeIsNotNull() {
            addCriterion("task_type is not null");
            return (Criteria) this;
        }

        public Criteria andTaskTypeEqualTo(String value) {
            addCriterion("task_type =", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotEqualTo(String value) {
            addCriterion("task_type <>", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeGreaterThan(String value) {
            addCriterion("task_type >", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeGreaterThanOrEqualTo(String value) {
            addCriterion("task_type >=", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLessThan(String value) {
            addCriterion("task_type <", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLessThanOrEqualTo(String value) {
            addCriterion("task_type <=", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLike(String value) {
            addCriterion("task_type like", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotLike(String value) {
            addCriterion("task_type not like", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeIn(List<String> values) {
            addCriterion("task_type in", values, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotIn(List<String> values) {
            addCriterion("task_type not in", values, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeBetween(String value1, String value2) {
            addCriterion("task_type between", value1, value2, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotBetween(String value1, String value2) {
            addCriterion("task_type not between", value1, value2, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskExecuteTypeIsNull() {
            addCriterion("task_execute_type is null");
            return (Criteria) this;
        }

        public Criteria andTaskExecuteTypeIsNotNull() {
            addCriterion("task_execute_type is not null");
            return (Criteria) this;
        }

        public Criteria andTaskExecuteTypeEqualTo(Integer value) {
            addCriterion("task_execute_type =", value, "taskExecuteType");
            return (Criteria) this;
        }

        public Criteria andTaskExecuteTypeNotEqualTo(Integer value) {
            addCriterion("task_execute_type <>", value, "taskExecuteType");
            return (Criteria) this;
        }

        public Criteria andTaskExecuteTypeGreaterThan(Integer value) {
            addCriterion("task_execute_type >", value, "taskExecuteType");
            return (Criteria) this;
        }

        public Criteria andTaskExecuteTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("task_execute_type >=", value, "taskExecuteType");
            return (Criteria) this;
        }

        public Criteria andTaskExecuteTypeLessThan(Integer value) {
            addCriterion("task_execute_type <", value, "taskExecuteType");
            return (Criteria) this;
        }

        public Criteria andTaskExecuteTypeLessThanOrEqualTo(Integer value) {
            addCriterion("task_execute_type <=", value, "taskExecuteType");
            return (Criteria) this;
        }

        public Criteria andTaskExecuteTypeIn(List<Integer> values) {
            addCriterion("task_execute_type in", values, "taskExecuteType");
            return (Criteria) this;
        }

        public Criteria andTaskExecuteTypeNotIn(List<Integer> values) {
            addCriterion("task_execute_type not in", values, "taskExecuteType");
            return (Criteria) this;
        }

        public Criteria andTaskExecuteTypeBetween(Integer value1, Integer value2) {
            addCriterion("task_execute_type between", value1, value2, "taskExecuteType");
            return (Criteria) this;
        }

        public Criteria andTaskExecuteTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("task_execute_type not between", value1, value2, "taskExecuteType");
            return (Criteria) this;
        }

        public Criteria andTaskParamsIsNull() {
            addCriterion("task_params is null");
            return (Criteria) this;
        }

        public Criteria andTaskParamsIsNotNull() {
            addCriterion("task_params is not null");
            return (Criteria) this;
        }

        public Criteria andTaskParamsEqualTo(String value) {
            addCriterion("task_params =", value, "taskParams");
            return (Criteria) this;
        }

        public Criteria andTaskParamsNotEqualTo(String value) {
            addCriterion("task_params <>", value, "taskParams");
            return (Criteria) this;
        }

        public Criteria andTaskParamsGreaterThan(String value) {
            addCriterion("task_params >", value, "taskParams");
            return (Criteria) this;
        }

        public Criteria andTaskParamsGreaterThanOrEqualTo(String value) {
            addCriterion("task_params >=", value, "taskParams");
            return (Criteria) this;
        }

        public Criteria andTaskParamsLessThan(String value) {
            addCriterion("task_params <", value, "taskParams");
            return (Criteria) this;
        }

        public Criteria andTaskParamsLessThanOrEqualTo(String value) {
            addCriterion("task_params <=", value, "taskParams");
            return (Criteria) this;
        }

        public Criteria andTaskParamsLike(String value) {
            addCriterion("task_params like", value, "taskParams");
            return (Criteria) this;
        }

        public Criteria andTaskParamsNotLike(String value) {
            addCriterion("task_params not like", value, "taskParams");
            return (Criteria) this;
        }

        public Criteria andTaskParamsIn(List<String> values) {
            addCriterion("task_params in", values, "taskParams");
            return (Criteria) this;
        }

        public Criteria andTaskParamsNotIn(List<String> values) {
            addCriterion("task_params not in", values, "taskParams");
            return (Criteria) this;
        }

        public Criteria andTaskParamsBetween(String value1, String value2) {
            addCriterion("task_params between", value1, value2, "taskParams");
            return (Criteria) this;
        }

        public Criteria andTaskParamsNotBetween(String value1, String value2) {
            addCriterion("task_params not between", value1, value2, "taskParams");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("flag is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("flag is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(Integer value) {
            addCriterion("flag =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(Integer value) {
            addCriterion("flag <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(Integer value) {
            addCriterion("flag >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("flag >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(Integer value) {
            addCriterion("flag <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(Integer value) {
            addCriterion("flag <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<Integer> values) {
            addCriterion("flag in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<Integer> values) {
            addCriterion("flag not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(Integer value1, Integer value2) {
            addCriterion("flag between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("flag not between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andIsCacheIsNull() {
            addCriterion("is_cache is null");
            return (Criteria) this;
        }

        public Criteria andIsCacheIsNotNull() {
            addCriterion("is_cache is not null");
            return (Criteria) this;
        }

        public Criteria andIsCacheEqualTo(Integer value) {
            addCriterion("is_cache =", value, "isCache");
            return (Criteria) this;
        }

        public Criteria andIsCacheNotEqualTo(Integer value) {
            addCriterion("is_cache <>", value, "isCache");
            return (Criteria) this;
        }

        public Criteria andIsCacheGreaterThan(Integer value) {
            addCriterion("is_cache >", value, "isCache");
            return (Criteria) this;
        }

        public Criteria andIsCacheGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_cache >=", value, "isCache");
            return (Criteria) this;
        }

        public Criteria andIsCacheLessThan(Integer value) {
            addCriterion("is_cache <", value, "isCache");
            return (Criteria) this;
        }

        public Criteria andIsCacheLessThanOrEqualTo(Integer value) {
            addCriterion("is_cache <=", value, "isCache");
            return (Criteria) this;
        }

        public Criteria andIsCacheIn(List<Integer> values) {
            addCriterion("is_cache in", values, "isCache");
            return (Criteria) this;
        }

        public Criteria andIsCacheNotIn(List<Integer> values) {
            addCriterion("is_cache not in", values, "isCache");
            return (Criteria) this;
        }

        public Criteria andIsCacheBetween(Integer value1, Integer value2) {
            addCriterion("is_cache between", value1, value2, "isCache");
            return (Criteria) this;
        }

        public Criteria andIsCacheNotBetween(Integer value1, Integer value2) {
            addCriterion("is_cache not between", value1, value2, "isCache");
            return (Criteria) this;
        }

        public Criteria andTaskPriorityIsNull() {
            addCriterion("task_priority is null");
            return (Criteria) this;
        }

        public Criteria andTaskPriorityIsNotNull() {
            addCriterion("task_priority is not null");
            return (Criteria) this;
        }

        public Criteria andTaskPriorityEqualTo(Integer value) {
            addCriterion("task_priority =", value, "taskPriority");
            return (Criteria) this;
        }

        public Criteria andTaskPriorityNotEqualTo(Integer value) {
            addCriterion("task_priority <>", value, "taskPriority");
            return (Criteria) this;
        }

        public Criteria andTaskPriorityGreaterThan(Integer value) {
            addCriterion("task_priority >", value, "taskPriority");
            return (Criteria) this;
        }

        public Criteria andTaskPriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("task_priority >=", value, "taskPriority");
            return (Criteria) this;
        }

        public Criteria andTaskPriorityLessThan(Integer value) {
            addCriterion("task_priority <", value, "taskPriority");
            return (Criteria) this;
        }

        public Criteria andTaskPriorityLessThanOrEqualTo(Integer value) {
            addCriterion("task_priority <=", value, "taskPriority");
            return (Criteria) this;
        }

        public Criteria andTaskPriorityIn(List<Integer> values) {
            addCriterion("task_priority in", values, "taskPriority");
            return (Criteria) this;
        }

        public Criteria andTaskPriorityNotIn(List<Integer> values) {
            addCriterion("task_priority not in", values, "taskPriority");
            return (Criteria) this;
        }

        public Criteria andTaskPriorityBetween(Integer value1, Integer value2) {
            addCriterion("task_priority between", value1, value2, "taskPriority");
            return (Criteria) this;
        }

        public Criteria andTaskPriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("task_priority not between", value1, value2, "taskPriority");
            return (Criteria) this;
        }

        public Criteria andWorkerGroupIsNull() {
            addCriterion("worker_group is null");
            return (Criteria) this;
        }

        public Criteria andWorkerGroupIsNotNull() {
            addCriterion("worker_group is not null");
            return (Criteria) this;
        }

        public Criteria andWorkerGroupEqualTo(String value) {
            addCriterion("worker_group =", value, "workerGroup");
            return (Criteria) this;
        }

        public Criteria andWorkerGroupNotEqualTo(String value) {
            addCriterion("worker_group <>", value, "workerGroup");
            return (Criteria) this;
        }

        public Criteria andWorkerGroupGreaterThan(String value) {
            addCriterion("worker_group >", value, "workerGroup");
            return (Criteria) this;
        }

        public Criteria andWorkerGroupGreaterThanOrEqualTo(String value) {
            addCriterion("worker_group >=", value, "workerGroup");
            return (Criteria) this;
        }

        public Criteria andWorkerGroupLessThan(String value) {
            addCriterion("worker_group <", value, "workerGroup");
            return (Criteria) this;
        }

        public Criteria andWorkerGroupLessThanOrEqualTo(String value) {
            addCriterion("worker_group <=", value, "workerGroup");
            return (Criteria) this;
        }

        public Criteria andWorkerGroupLike(String value) {
            addCriterion("worker_group like", value, "workerGroup");
            return (Criteria) this;
        }

        public Criteria andWorkerGroupNotLike(String value) {
            addCriterion("worker_group not like", value, "workerGroup");
            return (Criteria) this;
        }

        public Criteria andWorkerGroupIn(List<String> values) {
            addCriterion("worker_group in", values, "workerGroup");
            return (Criteria) this;
        }

        public Criteria andWorkerGroupNotIn(List<String> values) {
            addCriterion("worker_group not in", values, "workerGroup");
            return (Criteria) this;
        }

        public Criteria andWorkerGroupBetween(String value1, String value2) {
            addCriterion("worker_group between", value1, value2, "workerGroup");
            return (Criteria) this;
        }

        public Criteria andWorkerGroupNotBetween(String value1, String value2) {
            addCriterion("worker_group not between", value1, value2, "workerGroup");
            return (Criteria) this;
        }

        public Criteria andEnvironmentCodeIsNull() {
            addCriterion("environment_code is null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentCodeIsNotNull() {
            addCriterion("environment_code is not null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentCodeEqualTo(Long value) {
            addCriterion("environment_code =", value, "environmentCode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentCodeNotEqualTo(Long value) {
            addCriterion("environment_code <>", value, "environmentCode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentCodeGreaterThan(Long value) {
            addCriterion("environment_code >", value, "environmentCode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("environment_code >=", value, "environmentCode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentCodeLessThan(Long value) {
            addCriterion("environment_code <", value, "environmentCode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentCodeLessThanOrEqualTo(Long value) {
            addCriterion("environment_code <=", value, "environmentCode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentCodeIn(List<Long> values) {
            addCriterion("environment_code in", values, "environmentCode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentCodeNotIn(List<Long> values) {
            addCriterion("environment_code not in", values, "environmentCode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentCodeBetween(Long value1, Long value2) {
            addCriterion("environment_code between", value1, value2, "environmentCode");
            return (Criteria) this;
        }

        public Criteria andEnvironmentCodeNotBetween(Long value1, Long value2) {
            addCriterion("environment_code not between", value1, value2, "environmentCode");
            return (Criteria) this;
        }

        public Criteria andFailRetryTimesIsNull() {
            addCriterion("fail_retry_times is null");
            return (Criteria) this;
        }

        public Criteria andFailRetryTimesIsNotNull() {
            addCriterion("fail_retry_times is not null");
            return (Criteria) this;
        }

        public Criteria andFailRetryTimesEqualTo(Integer value) {
            addCriterion("fail_retry_times =", value, "failRetryTimes");
            return (Criteria) this;
        }

        public Criteria andFailRetryTimesNotEqualTo(Integer value) {
            addCriterion("fail_retry_times <>", value, "failRetryTimes");
            return (Criteria) this;
        }

        public Criteria andFailRetryTimesGreaterThan(Integer value) {
            addCriterion("fail_retry_times >", value, "failRetryTimes");
            return (Criteria) this;
        }

        public Criteria andFailRetryTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("fail_retry_times >=", value, "failRetryTimes");
            return (Criteria) this;
        }

        public Criteria andFailRetryTimesLessThan(Integer value) {
            addCriterion("fail_retry_times <", value, "failRetryTimes");
            return (Criteria) this;
        }

        public Criteria andFailRetryTimesLessThanOrEqualTo(Integer value) {
            addCriterion("fail_retry_times <=", value, "failRetryTimes");
            return (Criteria) this;
        }

        public Criteria andFailRetryTimesIn(List<Integer> values) {
            addCriterion("fail_retry_times in", values, "failRetryTimes");
            return (Criteria) this;
        }

        public Criteria andFailRetryTimesNotIn(List<Integer> values) {
            addCriterion("fail_retry_times not in", values, "failRetryTimes");
            return (Criteria) this;
        }

        public Criteria andFailRetryTimesBetween(Integer value1, Integer value2) {
            addCriterion("fail_retry_times between", value1, value2, "failRetryTimes");
            return (Criteria) this;
        }

        public Criteria andFailRetryTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("fail_retry_times not between", value1, value2, "failRetryTimes");
            return (Criteria) this;
        }

        public Criteria andFailRetryIntervalIsNull() {
            addCriterion("fail_retry_interval is null");
            return (Criteria) this;
        }

        public Criteria andFailRetryIntervalIsNotNull() {
            addCriterion("fail_retry_interval is not null");
            return (Criteria) this;
        }

        public Criteria andFailRetryIntervalEqualTo(Integer value) {
            addCriterion("fail_retry_interval =", value, "failRetryInterval");
            return (Criteria) this;
        }

        public Criteria andFailRetryIntervalNotEqualTo(Integer value) {
            addCriterion("fail_retry_interval <>", value, "failRetryInterval");
            return (Criteria) this;
        }

        public Criteria andFailRetryIntervalGreaterThan(Integer value) {
            addCriterion("fail_retry_interval >", value, "failRetryInterval");
            return (Criteria) this;
        }

        public Criteria andFailRetryIntervalGreaterThanOrEqualTo(Integer value) {
            addCriterion("fail_retry_interval >=", value, "failRetryInterval");
            return (Criteria) this;
        }

        public Criteria andFailRetryIntervalLessThan(Integer value) {
            addCriterion("fail_retry_interval <", value, "failRetryInterval");
            return (Criteria) this;
        }

        public Criteria andFailRetryIntervalLessThanOrEqualTo(Integer value) {
            addCriterion("fail_retry_interval <=", value, "failRetryInterval");
            return (Criteria) this;
        }

        public Criteria andFailRetryIntervalIn(List<Integer> values) {
            addCriterion("fail_retry_interval in", values, "failRetryInterval");
            return (Criteria) this;
        }

        public Criteria andFailRetryIntervalNotIn(List<Integer> values) {
            addCriterion("fail_retry_interval not in", values, "failRetryInterval");
            return (Criteria) this;
        }

        public Criteria andFailRetryIntervalBetween(Integer value1, Integer value2) {
            addCriterion("fail_retry_interval between", value1, value2, "failRetryInterval");
            return (Criteria) this;
        }

        public Criteria andFailRetryIntervalNotBetween(Integer value1, Integer value2) {
            addCriterion("fail_retry_interval not between", value1, value2, "failRetryInterval");
            return (Criteria) this;
        }

        public Criteria andTimeoutFlagIsNull() {
            addCriterion("timeout_flag is null");
            return (Criteria) this;
        }

        public Criteria andTimeoutFlagIsNotNull() {
            addCriterion("timeout_flag is not null");
            return (Criteria) this;
        }

        public Criteria andTimeoutFlagEqualTo(Integer value) {
            addCriterion("timeout_flag =", value, "timeoutFlag");
            return (Criteria) this;
        }

        public Criteria andTimeoutFlagNotEqualTo(Integer value) {
            addCriterion("timeout_flag <>", value, "timeoutFlag");
            return (Criteria) this;
        }

        public Criteria andTimeoutFlagGreaterThan(Integer value) {
            addCriterion("timeout_flag >", value, "timeoutFlag");
            return (Criteria) this;
        }

        public Criteria andTimeoutFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("timeout_flag >=", value, "timeoutFlag");
            return (Criteria) this;
        }

        public Criteria andTimeoutFlagLessThan(Integer value) {
            addCriterion("timeout_flag <", value, "timeoutFlag");
            return (Criteria) this;
        }

        public Criteria andTimeoutFlagLessThanOrEqualTo(Integer value) {
            addCriterion("timeout_flag <=", value, "timeoutFlag");
            return (Criteria) this;
        }

        public Criteria andTimeoutFlagIn(List<Integer> values) {
            addCriterion("timeout_flag in", values, "timeoutFlag");
            return (Criteria) this;
        }

        public Criteria andTimeoutFlagNotIn(List<Integer> values) {
            addCriterion("timeout_flag not in", values, "timeoutFlag");
            return (Criteria) this;
        }

        public Criteria andTimeoutFlagBetween(Integer value1, Integer value2) {
            addCriterion("timeout_flag between", value1, value2, "timeoutFlag");
            return (Criteria) this;
        }

        public Criteria andTimeoutFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("timeout_flag not between", value1, value2, "timeoutFlag");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotifyStrategyIsNull() {
            addCriterion("timeout_notify_strategy is null");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotifyStrategyIsNotNull() {
            addCriterion("timeout_notify_strategy is not null");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotifyStrategyEqualTo(Integer value) {
            addCriterion("timeout_notify_strategy =", value, "timeoutNotifyStrategy");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotifyStrategyNotEqualTo(Integer value) {
            addCriterion("timeout_notify_strategy <>", value, "timeoutNotifyStrategy");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotifyStrategyGreaterThan(Integer value) {
            addCriterion("timeout_notify_strategy >", value, "timeoutNotifyStrategy");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotifyStrategyGreaterThanOrEqualTo(Integer value) {
            addCriterion("timeout_notify_strategy >=", value, "timeoutNotifyStrategy");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotifyStrategyLessThan(Integer value) {
            addCriterion("timeout_notify_strategy <", value, "timeoutNotifyStrategy");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotifyStrategyLessThanOrEqualTo(Integer value) {
            addCriterion("timeout_notify_strategy <=", value, "timeoutNotifyStrategy");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotifyStrategyIn(List<Integer> values) {
            addCriterion("timeout_notify_strategy in", values, "timeoutNotifyStrategy");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotifyStrategyNotIn(List<Integer> values) {
            addCriterion("timeout_notify_strategy not in", values, "timeoutNotifyStrategy");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotifyStrategyBetween(Integer value1, Integer value2) {
            addCriterion("timeout_notify_strategy between", value1, value2, "timeoutNotifyStrategy");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotifyStrategyNotBetween(Integer value1, Integer value2) {
            addCriterion("timeout_notify_strategy not between", value1, value2, "timeoutNotifyStrategy");
            return (Criteria) this;
        }

        public Criteria andTimeoutIsNull() {
            addCriterion("timeout is null");
            return (Criteria) this;
        }

        public Criteria andTimeoutIsNotNull() {
            addCriterion("timeout is not null");
            return (Criteria) this;
        }

        public Criteria andTimeoutEqualTo(Integer value) {
            addCriterion("timeout =", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotEqualTo(Integer value) {
            addCriterion("timeout <>", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutGreaterThan(Integer value) {
            addCriterion("timeout >", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutGreaterThanOrEqualTo(Integer value) {
            addCriterion("timeout >=", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutLessThan(Integer value) {
            addCriterion("timeout <", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutLessThanOrEqualTo(Integer value) {
            addCriterion("timeout <=", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutIn(List<Integer> values) {
            addCriterion("timeout in", values, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotIn(List<Integer> values) {
            addCriterion("timeout not in", values, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutBetween(Integer value1, Integer value2) {
            addCriterion("timeout between", value1, value2, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotBetween(Integer value1, Integer value2) {
            addCriterion("timeout not between", value1, value2, "timeout");
            return (Criteria) this;
        }

        public Criteria andDelayTimeIsNull() {
            addCriterion("delay_time is null");
            return (Criteria) this;
        }

        public Criteria andDelayTimeIsNotNull() {
            addCriterion("delay_time is not null");
            return (Criteria) this;
        }

        public Criteria andDelayTimeEqualTo(Integer value) {
            addCriterion("delay_time =", value, "delayTime");
            return (Criteria) this;
        }

        public Criteria andDelayTimeNotEqualTo(Integer value) {
            addCriterion("delay_time <>", value, "delayTime");
            return (Criteria) this;
        }

        public Criteria andDelayTimeGreaterThan(Integer value) {
            addCriterion("delay_time >", value, "delayTime");
            return (Criteria) this;
        }

        public Criteria andDelayTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("delay_time >=", value, "delayTime");
            return (Criteria) this;
        }

        public Criteria andDelayTimeLessThan(Integer value) {
            addCriterion("delay_time <", value, "delayTime");
            return (Criteria) this;
        }

        public Criteria andDelayTimeLessThanOrEqualTo(Integer value) {
            addCriterion("delay_time <=", value, "delayTime");
            return (Criteria) this;
        }

        public Criteria andDelayTimeIn(List<Integer> values) {
            addCriterion("delay_time in", values, "delayTime");
            return (Criteria) this;
        }

        public Criteria andDelayTimeNotIn(List<Integer> values) {
            addCriterion("delay_time not in", values, "delayTime");
            return (Criteria) this;
        }

        public Criteria andDelayTimeBetween(Integer value1, Integer value2) {
            addCriterion("delay_time between", value1, value2, "delayTime");
            return (Criteria) this;
        }

        public Criteria andDelayTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("delay_time not between", value1, value2, "delayTime");
            return (Criteria) this;
        }

        public Criteria andTaskGroupIdIsNull() {
            addCriterion("task_group_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskGroupIdIsNotNull() {
            addCriterion("task_group_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskGroupIdEqualTo(Integer value) {
            addCriterion("task_group_id =", value, "taskGroupId");
            return (Criteria) this;
        }

        public Criteria andTaskGroupIdNotEqualTo(Integer value) {
            addCriterion("task_group_id <>", value, "taskGroupId");
            return (Criteria) this;
        }

        public Criteria andTaskGroupIdGreaterThan(Integer value) {
            addCriterion("task_group_id >", value, "taskGroupId");
            return (Criteria) this;
        }

        public Criteria andTaskGroupIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("task_group_id >=", value, "taskGroupId");
            return (Criteria) this;
        }

        public Criteria andTaskGroupIdLessThan(Integer value) {
            addCriterion("task_group_id <", value, "taskGroupId");
            return (Criteria) this;
        }

        public Criteria andTaskGroupIdLessThanOrEqualTo(Integer value) {
            addCriterion("task_group_id <=", value, "taskGroupId");
            return (Criteria) this;
        }

        public Criteria andTaskGroupIdIn(List<Integer> values) {
            addCriterion("task_group_id in", values, "taskGroupId");
            return (Criteria) this;
        }

        public Criteria andTaskGroupIdNotIn(List<Integer> values) {
            addCriterion("task_group_id not in", values, "taskGroupId");
            return (Criteria) this;
        }

        public Criteria andTaskGroupIdBetween(Integer value1, Integer value2) {
            addCriterion("task_group_id between", value1, value2, "taskGroupId");
            return (Criteria) this;
        }

        public Criteria andTaskGroupIdNotBetween(Integer value1, Integer value2) {
            addCriterion("task_group_id not between", value1, value2, "taskGroupId");
            return (Criteria) this;
        }

        public Criteria andTaskGroupPriorityIsNull() {
            addCriterion("task_group_priority is null");
            return (Criteria) this;
        }

        public Criteria andTaskGroupPriorityIsNotNull() {
            addCriterion("task_group_priority is not null");
            return (Criteria) this;
        }

        public Criteria andTaskGroupPriorityEqualTo(Integer value) {
            addCriterion("task_group_priority =", value, "taskGroupPriority");
            return (Criteria) this;
        }

        public Criteria andTaskGroupPriorityNotEqualTo(Integer value) {
            addCriterion("task_group_priority <>", value, "taskGroupPriority");
            return (Criteria) this;
        }

        public Criteria andTaskGroupPriorityGreaterThan(Integer value) {
            addCriterion("task_group_priority >", value, "taskGroupPriority");
            return (Criteria) this;
        }

        public Criteria andTaskGroupPriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("task_group_priority >=", value, "taskGroupPriority");
            return (Criteria) this;
        }

        public Criteria andTaskGroupPriorityLessThan(Integer value) {
            addCriterion("task_group_priority <", value, "taskGroupPriority");
            return (Criteria) this;
        }

        public Criteria andTaskGroupPriorityLessThanOrEqualTo(Integer value) {
            addCriterion("task_group_priority <=", value, "taskGroupPriority");
            return (Criteria) this;
        }

        public Criteria andTaskGroupPriorityIn(List<Integer> values) {
            addCriterion("task_group_priority in", values, "taskGroupPriority");
            return (Criteria) this;
        }

        public Criteria andTaskGroupPriorityNotIn(List<Integer> values) {
            addCriterion("task_group_priority not in", values, "taskGroupPriority");
            return (Criteria) this;
        }

        public Criteria andTaskGroupPriorityBetween(Integer value1, Integer value2) {
            addCriterion("task_group_priority between", value1, value2, "taskGroupPriority");
            return (Criteria) this;
        }

        public Criteria andTaskGroupPriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("task_group_priority not between", value1, value2, "taskGroupPriority");
            return (Criteria) this;
        }

        public Criteria andResourceIdsIsNull() {
            addCriterion("resource_ids is null");
            return (Criteria) this;
        }

        public Criteria andResourceIdsIsNotNull() {
            addCriterion("resource_ids is not null");
            return (Criteria) this;
        }

        public Criteria andResourceIdsEqualTo(String value) {
            addCriterion("resource_ids =", value, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsNotEqualTo(String value) {
            addCriterion("resource_ids <>", value, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsGreaterThan(String value) {
            addCriterion("resource_ids >", value, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsGreaterThanOrEqualTo(String value) {
            addCriterion("resource_ids >=", value, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsLessThan(String value) {
            addCriterion("resource_ids <", value, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsLessThanOrEqualTo(String value) {
            addCriterion("resource_ids <=", value, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsLike(String value) {
            addCriterion("resource_ids like", value, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsNotLike(String value) {
            addCriterion("resource_ids not like", value, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsIn(List<String> values) {
            addCriterion("resource_ids in", values, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsNotIn(List<String> values) {
            addCriterion("resource_ids not in", values, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsBetween(String value1, String value2) {
            addCriterion("resource_ids between", value1, value2, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsNotBetween(String value1, String value2) {
            addCriterion("resource_ids not between", value1, value2, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andCpuQuotaIsNull() {
            addCriterion("cpu_quota is null");
            return (Criteria) this;
        }

        public Criteria andCpuQuotaIsNotNull() {
            addCriterion("cpu_quota is not null");
            return (Criteria) this;
        }

        public Criteria andCpuQuotaEqualTo(Integer value) {
            addCriterion("cpu_quota =", value, "cpuQuota");
            return (Criteria) this;
        }

        public Criteria andCpuQuotaNotEqualTo(Integer value) {
            addCriterion("cpu_quota <>", value, "cpuQuota");
            return (Criteria) this;
        }

        public Criteria andCpuQuotaGreaterThan(Integer value) {
            addCriterion("cpu_quota >", value, "cpuQuota");
            return (Criteria) this;
        }

        public Criteria andCpuQuotaGreaterThanOrEqualTo(Integer value) {
            addCriterion("cpu_quota >=", value, "cpuQuota");
            return (Criteria) this;
        }

        public Criteria andCpuQuotaLessThan(Integer value) {
            addCriterion("cpu_quota <", value, "cpuQuota");
            return (Criteria) this;
        }

        public Criteria andCpuQuotaLessThanOrEqualTo(Integer value) {
            addCriterion("cpu_quota <=", value, "cpuQuota");
            return (Criteria) this;
        }

        public Criteria andCpuQuotaIn(List<Integer> values) {
            addCriterion("cpu_quota in", values, "cpuQuota");
            return (Criteria) this;
        }

        public Criteria andCpuQuotaNotIn(List<Integer> values) {
            addCriterion("cpu_quota not in", values, "cpuQuota");
            return (Criteria) this;
        }

        public Criteria andCpuQuotaBetween(Integer value1, Integer value2) {
            addCriterion("cpu_quota between", value1, value2, "cpuQuota");
            return (Criteria) this;
        }

        public Criteria andCpuQuotaNotBetween(Integer value1, Integer value2) {
            addCriterion("cpu_quota not between", value1, value2, "cpuQuota");
            return (Criteria) this;
        }

        public Criteria andMemoryMaxIsNull() {
            addCriterion("memory_max is null");
            return (Criteria) this;
        }

        public Criteria andMemoryMaxIsNotNull() {
            addCriterion("memory_max is not null");
            return (Criteria) this;
        }

        public Criteria andMemoryMaxEqualTo(Integer value) {
            addCriterion("memory_max =", value, "memoryMax");
            return (Criteria) this;
        }

        public Criteria andMemoryMaxNotEqualTo(Integer value) {
            addCriterion("memory_max <>", value, "memoryMax");
            return (Criteria) this;
        }

        public Criteria andMemoryMaxGreaterThan(Integer value) {
            addCriterion("memory_max >", value, "memoryMax");
            return (Criteria) this;
        }

        public Criteria andMemoryMaxGreaterThanOrEqualTo(Integer value) {
            addCriterion("memory_max >=", value, "memoryMax");
            return (Criteria) this;
        }

        public Criteria andMemoryMaxLessThan(Integer value) {
            addCriterion("memory_max <", value, "memoryMax");
            return (Criteria) this;
        }

        public Criteria andMemoryMaxLessThanOrEqualTo(Integer value) {
            addCriterion("memory_max <=", value, "memoryMax");
            return (Criteria) this;
        }

        public Criteria andMemoryMaxIn(List<Integer> values) {
            addCriterion("memory_max in", values, "memoryMax");
            return (Criteria) this;
        }

        public Criteria andMemoryMaxNotIn(List<Integer> values) {
            addCriterion("memory_max not in", values, "memoryMax");
            return (Criteria) this;
        }

        public Criteria andMemoryMaxBetween(Integer value1, Integer value2) {
            addCriterion("memory_max between", value1, value2, "memoryMax");
            return (Criteria) this;
        }

        public Criteria andMemoryMaxNotBetween(Integer value1, Integer value2) {
            addCriterion("memory_max not between", value1, value2, "memoryMax");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.t_ds_task_definition
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.t_ds_task_definition
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}