package com.example.scheduler.model.autoGenerated;

import java.io.Serializable;
import java.util.Date;

public class TDsTaskGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_task_group.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_task_group.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_task_group.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_task_group.group_size
     *
     * @mbg.generated
     */
    private Integer groupSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_task_group.project_code
     *
     * @mbg.generated
     */
    private Long projectCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_task_group.use_size
     *
     * @mbg.generated
     */
    private Integer useSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_task_group.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_task_group.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_task_group.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_ds_task_group.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.t_ds_task_group
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_task_group.id
     *
     * @return the value of public.t_ds_task_group.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_task_group.id
     *
     * @param id the value for public.t_ds_task_group.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_task_group.name
     *
     * @return the value of public.t_ds_task_group.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_task_group.name
     *
     * @param name the value for public.t_ds_task_group.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_task_group.description
     *
     * @return the value of public.t_ds_task_group.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_task_group.description
     *
     * @param description the value for public.t_ds_task_group.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_task_group.group_size
     *
     * @return the value of public.t_ds_task_group.group_size
     *
     * @mbg.generated
     */
    public Integer getGroupSize() {
        return groupSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_task_group.group_size
     *
     * @param groupSize the value for public.t_ds_task_group.group_size
     *
     * @mbg.generated
     */
    public void setGroupSize(Integer groupSize) {
        this.groupSize = groupSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_task_group.project_code
     *
     * @return the value of public.t_ds_task_group.project_code
     *
     * @mbg.generated
     */
    public Long getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_task_group.project_code
     *
     * @param projectCode the value for public.t_ds_task_group.project_code
     *
     * @mbg.generated
     */
    public void setProjectCode(Long projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_task_group.use_size
     *
     * @return the value of public.t_ds_task_group.use_size
     *
     * @mbg.generated
     */
    public Integer getUseSize() {
        return useSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_task_group.use_size
     *
     * @param useSize the value for public.t_ds_task_group.use_size
     *
     * @mbg.generated
     */
    public void setUseSize(Integer useSize) {
        this.useSize = useSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_task_group.user_id
     *
     * @return the value of public.t_ds_task_group.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_task_group.user_id
     *
     * @param userId the value for public.t_ds_task_group.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_task_group.status
     *
     * @return the value of public.t_ds_task_group.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_task_group.status
     *
     * @param status the value for public.t_ds_task_group.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_task_group.create_time
     *
     * @return the value of public.t_ds_task_group.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_task_group.create_time
     *
     * @param createTime the value for public.t_ds_task_group.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_ds_task_group.update_time
     *
     * @return the value of public.t_ds_task_group.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_ds_task_group.update_time
     *
     * @param updateTime the value for public.t_ds_task_group.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_group
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", groupSize=").append(groupSize);
        sb.append(", projectCode=").append(projectCode);
        sb.append(", useSize=").append(useSize);
        sb.append(", userId=").append(userId);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}