import {
  CodeOutlined,
  ApartmentOutlined,
  CloudServerOutlined,
  DatabaseOutlined,
  ForkOutlined,
  NodeIndexOutlined,
  SendOutlined,
  PartitionOutlined,
  DeploymentUnitOutlined,
  CloudOutlined,
  ExperimentOutlined,
  GithubOutlined,
  ReadOutlined,
  RocketOutlined,
  SettingOutlined,
} from '@ant-design/icons';

export const taskTypes = [
  { label: 'Shell', type: 'SHELL', command: 'echo "Hello"', category: 'general', icon: CodeOutlined },
  { label: 'Python', type: 'PYTHON', command: 'print("Hello")', category: 'general', icon: CodeOutlined },
  { label: 'Conditions', type: 'CONDITIONS', command: '', category: 'control_flow', icon: ApartmentOutlined },
  { label: 'Switch', type: 'SWITCH', command: '', category: 'control_flow', icon: ForkOutlined },
  { label: 'Dependent', type: 'DEPENDENT', command: '', category: 'control_flow', icon: NodeIndexOutlined },
  { label: 'Sub Process', type: 'SUB_PROCESS', command: '', category: 'control_flow', icon: PartitionOutlined },
  { 
    label: 'SQL', 
    type: 'SQL', 
    category: 'data', 
    icon: DatabaseOutlined,
    default_params: {
      datasource_name: 'db',
      sql_type: '0',
      sql: 'SELECT * FROM table',
      pre_sql: '',
      post_sql: '',
      display_rows: 10,
    } 
  },
  { label: 'DataX', type: 'DATAX', command: '', category: 'data', icon: SendOutlined },
  { label: 'Spark', type: 'SPARK', command: '', category: 'big_data', icon: RocketOutlined },
  { label: 'Flink', type: 'FLINK', command: '', category: 'big_data', icon: RocketOutlined },
  { label: 'Map Reduce', type: 'MR', command: '', category: 'big_data', icon: RocketOutlined },
  { label: 'Kubernetes', type: 'K8S', command: '', category: 'cloud_ml', icon: DeploymentUnitOutlined },
  { label: 'SageMaker', type: 'SAGEMAKER', command: '', category: 'cloud_ml', icon: CloudOutlined },
  { label: 'MLflow', type: 'MLFLOW', command: '', category: 'cloud_ml', icon: ExperimentOutlined },
  { label: 'OpenMLDB', type: 'OPENMLDB', command: '', category: 'cloud_ml', icon: ReadOutlined },
  { label: 'PyTorch', type: 'PYTORCH', command: '', category: 'cloud_ml', icon: GithubOutlined },
  { label: 'DVC', type: 'DVC', command: '', category: 'cloud_ml', icon: GithubOutlined },
  { label: 'HTTP', type: 'HTTP', command: 'curl http://example.com', category: 'other', icon: CloudServerOutlined },
  { label: 'Procedure', type: 'PROCEDURE', command: '', category: 'other', icon: SettingOutlined },
];

export const taskCategories = [
  { key: 'general', label: 'General' },
  { key: 'control_flow', label: 'Control Flow' },
  { key: 'data', label: 'Data' },
  { key: 'big_data', label: 'Big Data' },
  { key: 'cloud_ml', label: 'Cloud/ML' },
  { key: 'other', label: 'Other' },
];
