package com.example.scheduler.mapper.autoGenerated;

import com.example.scheduler.model.autoGenerated.EtlTaskMock;
import com.example.scheduler.model.autoGenerated.EtlTaskMockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EtlTaskMockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etl_task_mock
     *
     * @mbg.generated
     */
    long countByExample(EtlTaskMockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etl_task_mock
     *
     * @mbg.generated
     */
    int deleteByExample(EtlTaskMockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etl_task_mock
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etl_task_mock
     *
     * @mbg.generated
     */
    int insert(EtlTaskMock row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etl_task_mock
     *
     * @mbg.generated
     */
    int insertSelective(EtlTaskMock row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etl_task_mock
     *
     * @mbg.generated
     */
    List<EtlTaskMock> selectByExample(EtlTaskMockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etl_task_mock
     *
     * @mbg.generated
     */
    EtlTaskMock selectByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etl_task_mock
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") EtlTaskMock row, @Param("example") EtlTaskMockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etl_task_mock
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") EtlTaskMock row, @Param("example") EtlTaskMockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etl_task_mock
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EtlTaskMock row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etl_task_mock
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EtlTaskMock row);
}