package com.example.scheduler.mapper.autoGenerated;

import com.example.scheduler.model.autoGenerated.QrtzFiredTriggers;
import com.example.scheduler.model.autoGenerated.QrtzFiredTriggersExample;
import com.example.scheduler.model.autoGenerated.QrtzFiredTriggersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzFiredTriggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_fired_triggers
     *
     * @mbg.generated
     */
    long countByExample(QrtzFiredTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_fired_triggers
     *
     * @mbg.generated
     */
    int deleteByExample(QrtzFiredTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_fired_triggers
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(QrtzFiredTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_fired_triggers
     *
     * @mbg.generated
     */
    int insert(QrtzFiredTriggers row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_fired_triggers
     *
     * @mbg.generated
     */
    int insertSelective(QrtzFiredTriggers row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_fired_triggers
     *
     * @mbg.generated
     */
    List<QrtzFiredTriggers> selectByExample(QrtzFiredTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_fired_triggers
     *
     * @mbg.generated
     */
    QrtzFiredTriggers selectByPrimaryKey(QrtzFiredTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_fired_triggers
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") QrtzFiredTriggers row, @Param("example") QrtzFiredTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_fired_triggers
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") QrtzFiredTriggers row, @Param("example") QrtzFiredTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_fired_triggers
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QrtzFiredTriggers row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_fired_triggers
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QrtzFiredTriggers row);
}