package com.example.scheduler.mapper.autoGenerated;

import com.example.scheduler.model.autoGenerated.QrtzSchedulerState;
import com.example.scheduler.model.autoGenerated.QrtzSchedulerStateExample;
import com.example.scheduler.model.autoGenerated.QrtzSchedulerStateKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzSchedulerStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_scheduler_state
     *
     * @mbg.generated
     */
    long countByExample(QrtzSchedulerStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_scheduler_state
     *
     * @mbg.generated
     */
    int deleteByExample(QrtzSchedulerStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_scheduler_state
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(QrtzSchedulerStateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_scheduler_state
     *
     * @mbg.generated
     */
    int insert(QrtzSchedulerState row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_scheduler_state
     *
     * @mbg.generated
     */
    int insertSelective(QrtzSchedulerState row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_scheduler_state
     *
     * @mbg.generated
     */
    List<QrtzSchedulerState> selectByExample(QrtzSchedulerStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_scheduler_state
     *
     * @mbg.generated
     */
    QrtzSchedulerState selectByPrimaryKey(QrtzSchedulerStateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_scheduler_state
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") QrtzSchedulerState row, @Param("example") QrtzSchedulerStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_scheduler_state
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") QrtzSchedulerState row, @Param("example") QrtzSchedulerStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_scheduler_state
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QrtzSchedulerState row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.qrtz_scheduler_state
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QrtzSchedulerState row);
}