package com.example.scheduler.mapper.autoGenerated;

import com.example.scheduler.model.autoGenerated.TDsAccessToken;
import com.example.scheduler.model.autoGenerated.TDsAccessTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDsAccessTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_access_token
     *
     * @mbg.generated
     */
    long countByExample(TDsAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_access_token
     *
     * @mbg.generated
     */
    int deleteByExample(TDsAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_access_token
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_access_token
     *
     * @mbg.generated
     */
    int insert(TDsAccessToken row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_access_token
     *
     * @mbg.generated
     */
    int insertSelective(TDsAccessToken row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_access_token
     *
     * @mbg.generated
     */
    List<TDsAccessToken> selectByExample(TDsAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_access_token
     *
     * @mbg.generated
     */
    TDsAccessToken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_access_token
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TDsAccessToken row, @Param("example") TDsAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_access_token
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TDsAccessToken row, @Param("example") TDsAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_access_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TDsAccessToken row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_access_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TDsAccessToken row);
}