package com.example.scheduler.mapper.autoGenerated;

import com.example.scheduler.model.autoGenerated.TDsAlert;
import com.example.scheduler.model.autoGenerated.TDsAlertExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDsAlertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert
     *
     * @mbg.generated
     */
    long countByExample(TDsAlertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert
     *
     * @mbg.generated
     */
    int deleteByExample(TDsAlertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert
     *
     * @mbg.generated
     */
    int insert(TDsAlert row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert
     *
     * @mbg.generated
     */
    int insertSelective(TDsAlert row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert
     *
     * @mbg.generated
     */
    List<TDsAlert> selectByExample(TDsAlertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert
     *
     * @mbg.generated
     */
    TDsAlert selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TDsAlert row, @Param("example") TDsAlertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TDsAlert row, @Param("example") TDsAlertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TDsAlert row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_alert
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TDsAlert row);
}