package com.example.scheduler.mapper.autoGenerated;

import com.example.scheduler.model.autoGenerated.TDsDqComparisonType;
import com.example.scheduler.model.autoGenerated.TDsDqComparisonTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDsDqComparisonTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_comparison_type
     *
     * @mbg.generated
     */
    long countByExample(TDsDqComparisonTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_comparison_type
     *
     * @mbg.generated
     */
    int deleteByExample(TDsDqComparisonTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_comparison_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_comparison_type
     *
     * @mbg.generated
     */
    int insert(TDsDqComparisonType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_comparison_type
     *
     * @mbg.generated
     */
    int insertSelective(TDsDqComparisonType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_comparison_type
     *
     * @mbg.generated
     */
    List<TDsDqComparisonType> selectByExample(TDsDqComparisonTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_comparison_type
     *
     * @mbg.generated
     */
    TDsDqComparisonType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_comparison_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TDsDqComparisonType row, @Param("example") TDsDqComparisonTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_comparison_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TDsDqComparisonType row, @Param("example") TDsDqComparisonTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_comparison_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TDsDqComparisonType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_comparison_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TDsDqComparisonType row);
}