package com.example.scheduler.mapper.autoGenerated;

import com.example.scheduler.model.autoGenerated.TDsDqRule;
import com.example.scheduler.model.autoGenerated.TDsDqRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDsDqRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_rule
     *
     * @mbg.generated
     */
    long countByExample(TDsDqRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_rule
     *
     * @mbg.generated
     */
    int deleteByExample(TDsDqRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_rule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_rule
     *
     * @mbg.generated
     */
    int insert(TDsDqRule row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_rule
     *
     * @mbg.generated
     */
    int insertSelective(TDsDqRule row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_rule
     *
     * @mbg.generated
     */
    List<TDsDqRule> selectByExample(TDsDqRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_rule
     *
     * @mbg.generated
     */
    TDsDqRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_rule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TDsDqRule row, @Param("example") TDsDqRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_rule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TDsDqRule row, @Param("example") TDsDqRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TDsDqRule row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_dq_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TDsDqRule row);
}