package com.example.scheduler.mapper.autoGenerated;

import com.example.scheduler.model.autoGenerated.TDsPluginDefine;
import com.example.scheduler.model.autoGenerated.TDsPluginDefineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDsPluginDefineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_plugin_define
     *
     * @mbg.generated
     */
    long countByExample(TDsPluginDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_plugin_define
     *
     * @mbg.generated
     */
    int deleteByExample(TDsPluginDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_plugin_define
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_plugin_define
     *
     * @mbg.generated
     */
    int insert(TDsPluginDefine row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_plugin_define
     *
     * @mbg.generated
     */
    int insertSelective(TDsPluginDefine row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_plugin_define
     *
     * @mbg.generated
     */
    List<TDsPluginDefine> selectByExample(TDsPluginDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_plugin_define
     *
     * @mbg.generated
     */
    TDsPluginDefine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_plugin_define
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TDsPluginDefine row, @Param("example") TDsPluginDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_plugin_define
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TDsPluginDefine row, @Param("example") TDsPluginDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_plugin_define
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TDsPluginDefine row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_plugin_define
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TDsPluginDefine row);
}