package com.example.scheduler.mapper.autoGenerated;

import com.example.scheduler.model.autoGenerated.TDsRelationSubWorkflow;
import com.example.scheduler.model.autoGenerated.TDsRelationSubWorkflowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDsRelationSubWorkflowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_relation_sub_workflow
     *
     * @mbg.generated
     */
    long countByExample(TDsRelationSubWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_relation_sub_workflow
     *
     * @mbg.generated
     */
    int deleteByExample(TDsRelationSubWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_relation_sub_workflow
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_relation_sub_workflow
     *
     * @mbg.generated
     */
    int insert(TDsRelationSubWorkflow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_relation_sub_workflow
     *
     * @mbg.generated
     */
    int insertSelective(TDsRelationSubWorkflow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_relation_sub_workflow
     *
     * @mbg.generated
     */
    List<TDsRelationSubWorkflow> selectByExample(TDsRelationSubWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_relation_sub_workflow
     *
     * @mbg.generated
     */
    TDsRelationSubWorkflow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_relation_sub_workflow
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TDsRelationSubWorkflow row, @Param("example") TDsRelationSubWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_relation_sub_workflow
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TDsRelationSubWorkflow row, @Param("example") TDsRelationSubWorkflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_relation_sub_workflow
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TDsRelationSubWorkflow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_relation_sub_workflow
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TDsRelationSubWorkflow row);
}