package com.example.scheduler.mapper.autoGenerated;

import com.example.scheduler.model.autoGenerated.TDsSchedules;
import com.example.scheduler.model.autoGenerated.TDsSchedulesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDsSchedulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_schedules
     *
     * @mbg.generated
     */
    long countByExample(TDsSchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_schedules
     *
     * @mbg.generated
     */
    int deleteByExample(TDsSchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_schedules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_schedules
     *
     * @mbg.generated
     */
    int insert(TDsSchedules row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_schedules
     *
     * @mbg.generated
     */
    int insertSelective(TDsSchedules row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_schedules
     *
     * @mbg.generated
     */
    List<TDsSchedules> selectByExample(TDsSchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_schedules
     *
     * @mbg.generated
     */
    TDsSchedules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_schedules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TDsSchedules row, @Param("example") TDsSchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_schedules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TDsSchedules row, @Param("example") TDsSchedulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_schedules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TDsSchedules row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_schedules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TDsSchedules row);
}