package com.example.scheduler.mapper.autoGenerated;

import com.example.scheduler.model.autoGenerated.TDsTaskGroupQueue;
import com.example.scheduler.model.autoGenerated.TDsTaskGroupQueueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDsTaskGroupQueueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_group_queue
     *
     * @mbg.generated
     */
    long countByExample(TDsTaskGroupQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_group_queue
     *
     * @mbg.generated
     */
    int deleteByExample(TDsTaskGroupQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_group_queue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_group_queue
     *
     * @mbg.generated
     */
    int insert(TDsTaskGroupQueue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_group_queue
     *
     * @mbg.generated
     */
    int insertSelective(TDsTaskGroupQueue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_group_queue
     *
     * @mbg.generated
     */
    List<TDsTaskGroupQueue> selectByExample(TDsTaskGroupQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_group_queue
     *
     * @mbg.generated
     */
    TDsTaskGroupQueue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_group_queue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TDsTaskGroupQueue row, @Param("example") TDsTaskGroupQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_group_queue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TDsTaskGroupQueue row, @Param("example") TDsTaskGroupQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_group_queue
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TDsTaskGroupQueue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_ds_task_group_queue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TDsTaskGroupQueue row);
}